# Generated by Django 4.2.30 on 2026-06-25 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcuBackupRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17)),
                ('ecu_name', models.CharField(max_length=32)),
                ('memory_region', models.CharField(max_length=16)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('size', models.PositiveIntegerField()),
                ('path', models.CharField(max_length=512)),
                ('captured_at', models.DateTimeField()),
                ('uploaded_to_s3', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ECU Backup Reference',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='EcuPinoutDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecu_name', models.CharField(max_length=32, unique=True)),
                ('image_url', models.CharField(max_length=512)),
                ('callouts', models.JSONField(blank=True, default=list, help_text='[{"pin": 18, "label": "BOOT", "color": "red"}]')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ECU Pinout Diagram',
            },
        ),
        migrations.CreateModel(
            name='EcuSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17)),
                ('chassis', models.CharField(blank=True, help_text='F30, G20, ...', max_length=8)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('technician', models.CharField(blank=True, max_length=64)),
                ('transport_kind', models.CharField(blank=True, max_length=16)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ECU Session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WizardSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(db_index=True, max_length=32)),
                ('vin', models.CharField(db_index=True, max_length=17)),
                ('ecu_name', models.CharField(max_length=32)),
                ('captured_isn_hex', models.CharField(blank=True, max_length=128)),
                ('technician_id', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Wizard Session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('profile_name', models.CharField(db_index=True, max_length=32)),
                ('strategy', models.CharField(choices=[('software_only', 'Software Only'), ('hardware_automation', 'Hardware Automation'), ('interactive_guided', 'Interactive Guided')], db_index=True, max_length=24)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('suspended', 'Suspended'), ('failed_rolled_back', 'Failed (rolled back)'), ('failed_unrecoverable', 'Failed (unrecoverable)')], db_index=True, max_length=24)),
                ('exploit_used', models.CharField(blank=True, max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_attempts', to='bmw_ecu.ecusession')),
            ],
            options={
                'verbose_name': 'Execution Attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EcuStateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('connect', 'Connect'), ('session', 'Diagnostic session'), ('security', 'Security access'), ('read_isn', 'ISN read'), ('write_isn', 'ISN write'), ('ews_sync', 'EWS sync'), ('code', 'Coding'), ('flash_start', 'Flash start'), ('flash_done', 'Flash done'), ('rollback', 'Rollback'), ('error', 'Error')], db_index=True, max_length=24)),
                ('ecu_name', models.CharField(blank=True, max_length=32)),
                ('success', models.BooleanField(default=True)),
                ('backup_sha256', models.CharField(blank=True, db_index=True, help_text='Content-addressed reference to the on-disk dump', max_length=64)),
                ('payload_summary', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_changes', to='bmw_ecu.ecusession')),
            ],
            options={
                'verbose_name': 'ECU State Change',
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticFeeCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('status', models.CharField(choices=[('authorized', 'Authorized'), ('captured', 'Captured'), ('released', 'Released'), ('expired', 'Expired'), ('declined', 'Declined')], db_index=True, default='authorized', max_length=16)),
                ('authorization_ref', models.CharField(help_text='Idempotency key', max_length=64, unique=True)),
                ('authorized_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_charges', to='bmw_ecu.ecusession')),
            ],
            options={
                'verbose_name': 'Diagnostic Fee Charge',
                'ordering': ['-authorized_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='diagnosticfeecharge',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'authorized')), fields=('vin',), name='bmw_ecu_one_open_auth_per_vin'),
        ),
    ]
