# Generated by Django 4.2.30 on 2026-06-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmw_ecu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BmwEcuSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('wallet', 'Wallet Deduct'), ('paymob', 'Paymob Iframe'), ('failed', 'Settlement Failed')], db_index=True, max_length=16)),
                ('succeeded', models.BooleanField(db_index=True, default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('wallet_before', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('wallet_after', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('paymob_iframe_url', models.URLField(blank=True, max_length=1024)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('charge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='bmw_ecu.diagnosticfeecharge')),
            ],
            options={
                'verbose_name': 'BMW ECU Settlement',
                'ordering': ['-created_at'],
            },
        ),
    ]
