# Generated by Django 4.2.30 on 2026-06-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmw_ecu', '0002_bmwecusettlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingEntitlementHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17)),
                ('operation_type', models.CharField(db_index=True, max_length=16)),
                ('tenant_schema', models.CharField(blank=True, db_index=True, max_length=64)),
                ('hold_ref', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open (awaiting policy)'), ('converted', 'Converted to charge'), ('dropped', 'Dropped (not charged)')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Coding Entitlement Hold',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='diagnosticfeecharge',
            name='operation_type',
            field=models.CharField(db_index=True, default='isn', help_text='isn | coding', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='codingentitlementhold',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('vin', 'operation_type'), name='bmw_ecu_one_open_hold_per_vin_op'),
        ),
    ]
