# Generated by Django 4.2.30 on 2026-06-25 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmw_ecu', '0003_codingentitlementhold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(db_index=True, help_text='clients.Client.schema_name', max_length=64)),
                ('grant_type', models.CharField(choices=[('coding_credits', 'Coding credits (count)'), ('isn_credits', 'ISN credits (count)'), ('subscription_window', 'Subscription window (time-bounded)')], db_index=True, max_length=24)),
                ('credits_total', models.PositiveIntegerField(default=0, help_text='0 for time-based')),
                ('credits_remaining', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, help_text='null = no time bound', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('expired', 'Expired'), ('revoked', 'Revoked by admin')], db_index=True, default='active', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('granted_by', models.CharField(blank=True, help_text='username of issuing super-admin', max_length=64)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gift Credit',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AlterField(
            model_name='bmwecusettlement',
            name='mode',
            field=models.CharField(choices=[('gift', 'Gift Credit'), ('wallet', 'Wallet Deduct'), ('paymob', 'Paymob Iframe'), ('failed', 'Settlement Failed')], db_index=True, max_length=16),
        ),
        migrations.CreateModel(
            name='GiftCreditUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17)),
                ('operation_type', models.CharField(db_index=True, max_length=16)),
                ('used_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reference', models.CharField(blank=True, help_text='DiagnosticFeeCharge.authorization_ref', max_length=64)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='bmw_ecu.giftcredit')),
            ],
            options={
                'verbose_name': 'Gift Credit Usage',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='giftcredit',
            index=models.Index(fields=['tenant_schema', 'status', 'grant_type'], name='bmw_ecu_gif_tenant__be923b_idx'),
        ),
        migrations.AddField(
            model_name='bmwecusettlement',
            name='gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='bmw_ecu.giftcredit'),
        ),
    ]
