# Generated by Django 4.2.30 on 2026-06-26 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmw_ecu', '0004_giftcredit_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Stable machine identifier, e.g. 'frm_repair'.", max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('coding', 'Coding (CAFD / FA-VO)'), ('repair', 'Module Repair (FRM, footwell, BDC)'), ('key_programming', 'Key Programming'), ('isn_reset', 'ISN Reset (EGS / used module swap)'), ('crash_reset', 'Crash Reset (Airbag / SRS)'), ('battery', 'Battery / CBS Management'), ('flash', 'Flashing / Firmware'), ('diagnostic', 'Diagnostic / Read-only'), ('other', 'Other')], db_index=True, default='other', max_length=24)),
                ('default_operation_type', models.CharField(choices=[('coding', 'Coding'), ('isn', 'ISN'), ('flash', 'Flash'), ('repair', 'Repair'), ('reset', 'Reset')], default='coding', help_text='Coarse-grained op family — keeps the legacy ISN-vs-Coding gate happy.', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False hides this feature from new package bundles.')),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="e.g. 'pkg_key_master', 'pkg_full_suite'.", max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('billing_mode', models.CharField(choices=[('time', 'Time-bound (e.g. 30 days)'), ('usage', 'Usage-bound (e.g. 10 successful runs)'), ('hybrid', 'Hybrid (whichever runs out first)'), ('unlimited', 'Unlimited (lifetime)')], db_index=True, default='time', max_length=16)),
                ('default_duration_days', models.PositiveIntegerField(default=30, help_text='Time-bound: how long the grant is valid. 0 = unlimited.')),
                ('default_usage_quota', models.PositiveIntegerField(default=0, help_text='Usage-bound: total successful operations allowed. 0 = unlimited.')),
                ('price_egp', models.DecimalField(decimal_places=2, default=0, help_text='Sticker price the storefront card shows.', max_digits=10)),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False, help_text="Highlight on the storefront ('Most popular').")),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(blank=True, help_text='Atomic features bundled into this package.', related_name='packages', to='bmw_ecu.feature')),
            ],
            options={
                'verbose_name': 'Subscription Package',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TenantPackageGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(db_index=True, help_text='clients.Client.schema_name', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired (time)'), ('exhausted', 'Exhausted (usage)'), ('revoked', 'Revoked by admin')], db_index=True, default='active', max_length=16)),
                ('billing_mode', models.CharField(choices=[('time', 'Time-bound (e.g. 30 days)'), ('usage', 'Usage-bound (e.g. 10 successful runs)'), ('hybrid', 'Hybrid (whichever runs out first)'), ('unlimited', 'Unlimited (lifetime)')], db_index=True, default='time', max_length=16)),
                ('valid_from', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, help_text='null = unlimited time', null=True)),
                ('usage_quota', models.PositiveIntegerField(default=0, help_text='0 = unlimited usage')),
                ('usage_used', models.PositiveIntegerField(default=0)),
                ('price_paid_egp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('granted_by', models.CharField(blank=True, help_text="Super-admin username or 'paymob:<txn>'", max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_grants', to='bmw_ecu.subscriptionpackage')),
            ],
            options={
                'verbose_name': 'Tenant Package Grant',
                'ordering': ['-granted_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantFeatureGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(db_index=True, help_text='clients.Client.schema_name', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired (time)'), ('exhausted', 'Exhausted (usage)'), ('revoked', 'Revoked by admin')], db_index=True, default='active', max_length=16)),
                ('billing_mode', models.CharField(choices=[('time', 'Time-bound (e.g. 30 days)'), ('usage', 'Usage-bound (e.g. 10 successful runs)'), ('hybrid', 'Hybrid (whichever runs out first)'), ('unlimited', 'Unlimited (lifetime)')], db_index=True, default='time', max_length=16)),
                ('valid_from', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, help_text='null = unlimited time', null=True)),
                ('usage_quota', models.PositiveIntegerField(default=0, help_text='0 = unlimited usage')),
                ('usage_used', models.PositiveIntegerField(default=0)),
                ('price_paid_egp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('granted_by', models.CharField(blank=True, help_text="Super-admin username or 'paymob:<txn>'", max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_grants', to='bmw_ecu.feature')),
            ],
            options={
                'verbose_name': 'Tenant Feature Grant',
                'ordering': ['-granted_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(db_index=True, max_length=64)),
                ('grant_kind', models.CharField(choices=[('package', 'Package grant'), ('feature', 'Feature grant')], db_index=True, max_length=8)),
                ('vin', models.CharField(blank=True, db_index=True, max_length=17)),
                ('operation_ref', models.CharField(blank=True, help_text='DiagnosticFeeCharge.authorization_ref or session id', max_length=64)),
                ('used_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='bmw_ecu.feature')),
                ('feature_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='bmw_ecu.tenantfeaturegrant')),
                ('package_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='bmw_ecu.tenantpackagegrant')),
            ],
            options={
                'verbose_name': 'Feature Usage Event',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenantpackagegrant',
            index=models.Index(fields=['tenant_schema', 'status'], name='bmw_ecu_ten_tenant__0872be_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantpackagegrant',
            index=models.Index(fields=['tenant_schema', 'package', 'status'], name='bmw_ecu_ten_tenant__72bb5a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantfeaturegrant',
            index=models.Index(fields=['tenant_schema', 'status'], name='bmw_ecu_ten_tenant__cc526d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantfeaturegrant',
            index=models.Index(fields=['tenant_schema', 'feature', 'status'], name='bmw_ecu_ten_tenant__7fefca_idx'),
        ),
        migrations.AddIndex(
            model_name='featureusageevent',
            index=models.Index(fields=['tenant_schema', 'feature', 'used_at'], name='bmw_ecu_fea_tenant__aa1683_idx'),
        ),
    ]
