# Generated by Django 4.2.30 on 2026-06-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmw_ecu', '0006_seed_initial_features'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='featureusageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('operation_ref', ''), _negated=True), fields=('tenant_schema', 'feature', 'operation_ref'), name='bmw_ecu_unique_consume_per_op_ref'),
        ),
    ]
