# Generated by Django 4.2.30 on 2026-06-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmw_ecu', '0012_seed_ecu_flashing_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcuHardwareProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_id', models.CharField(help_text='Live HWEL / part number, e.g. 8606229', max_length=32, unique=True)),
                ('ecu_name', models.CharField(help_text='Marketing name, e.g. MEVD17.2.9', max_length=64)),
                ('board_revision', models.CharField(help_text='e.g. Rev B (N20 pre-LCI)', max_length=64)),
                ('family', models.CharField(blank=True, help_text='MEVD17 | FEM | CAS ...', max_length=32)),
                ('protocol', models.CharField(blank=True, help_text='BootMode | BDM | JTAG', max_length=32)),
                ('power_pin', models.PositiveIntegerField(help_text='KL30 / +12V')),
                ('ground_pin', models.PositiveIntegerField(help_text='KL31 / GND')),
                ('boot_pin', models.PositiveIntegerField(blank=True, help_text='Ground/probe to enter BSL/BDM', null=True)),
                ('can_h_pin', models.PositiveIntegerField(blank=True, null=True)),
                ('can_l_pin', models.PositiveIntegerField(blank=True, null=True)),
                ('k_line_pin', models.PositiveIntegerField(blank=True, null=True)),
                ('pcb_image_url', models.CharField(blank=True, help_text='Full PCB photo for orientation', max_length=512)),
                ('boot_image_url', models.CharField(blank=True, help_text='Close-up of the boot pad/pin', max_length=512)),
                ('callouts', models.JSONField(blank=True, default=list, help_text='[{"pin": 24, "label": "BOOT", "color": "yellow"}]')),
                ('physical_steps_ar', models.JSONField(blank=True, default=list, help_text='Variant-specific steps (Arabic)')),
                ('physical_steps_en', models.JSONField(blank=True, default=list, help_text='Variant-specific steps (English)')),
                ('notes', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False, help_text='True once confirmed on real hardware')),
            ],
            options={
                'verbose_name': 'ECU Hardware Profile (bench)',
            },
        ),
    ]
