# Generated by Django 4.2.30 on 2026-09-21 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0052_journalentry_branch"),
        ("hr", "0004_alter_aidesignsubscription_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="RobotDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="اسم الروبوت")),
                (
                    "device_uid",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="معرف الجهاز (ESP32 UID)",
                    ),
                ),
                (
                    "api_token",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="توكن الجهاز",
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل؟")),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر اتصال"
                    ),
                ),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robots",
                        to="inventory.branch",
                        verbose_name="الفرع",
                    ),
                ),
            ],
            options={
                "verbose_name": "جهاز روبوت",
                "verbose_name_plural": "🤖 أجهزة الروبوت",
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="RobotVoiceInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True, default="", verbose_name="النص المسموع"
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("inventory_query", "استعلام مخزون"),
                            ("pos_answer", "رد على سؤال بيع"),
                            ("diagnostic", "سؤال تشخيصي/عطل"),
                            ("command", "أمر حركة"),
                            ("unknown", "غير معروف"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "reply_text",
                    models.TextField(
                        blank=True, default="", verbose_name="الرد المنطوق"
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_turns",
                        to="robot.robotdevice",
                        verbose_name="الجهاز",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="robot_voice_turns",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاعل صوتي",
                "verbose_name_plural": "🎙️ التفاعلات الصوتية",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_on_hand", models.IntegerField(default=0)),
                ("min_stock_level", models.IntegerField(default=0)),
                ("suggested_reorder_qty", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "مفتوح"),
                            ("acknowledged", "مستلَم"),
                            ("queued", "مضاف للمنافيست"),
                            ("dismissed", "مُهمَل"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=15,
                    ),
                ),
                ("manifest_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_signals",
                        to="robot.robotdevice",
                        verbose_name="الجهاز",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robot_procurement_signals",
                        to="inventory.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشارة توريد",
                "verbose_name_plural": "📦 إشارات التوريد (Procurement Agent)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MotorCommandLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actuator",
                    models.CharField(
                        choices=[
                            ("head", "الرأس (لف يمين/شمال)"),
                            ("arm_left", "الذراع اليسرى"),
                            ("arm_right", "الذراع اليمنى"),
                            ("track", "الجنزير (حركة)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("left", "left"),
                            ("right", "right"),
                            ("up", "up"),
                            ("down", "down"),
                            ("forward", "forward"),
                            ("backward", "backward"),
                            ("stop", "stop"),
                        ],
                        max_length=10,
                    ),
                ),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                (
                    "acknowledged",
                    models.BooleanField(default=False, verbose_name="تم التنفيذ؟"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motor_commands",
                        to="robot.robotdevice",
                        verbose_name="الجهاز",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "أمر حركة",
                "verbose_name_plural": "🦾 أوامر الحركة",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RobotScanEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("pos", "بيع (POS)"),
                            ("scrap", "تقييم مستعمل/خردة"),
                            ("lookup", "استعلام مخزون"),
                        ],
                        default="pos",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="robot/scans/%Y/%m/",
                        verbose_name="صورة القطعة",
                    ),
                ),
                (
                    "recognized_label",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "recognized_part_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "confidence",
                    models.FloatField(default=0.0, verbose_name="درجة الثقة"),
                ),
                (
                    "condition_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="درجة الحالة"
                    ),
                ),
                (
                    "condition_notes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="ملاحظات الحالة"
                    ),
                ),
                (
                    "suggested_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="السعر المقترح (قطاعي)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="robot_scans",
                        to="hr.employee",
                        verbose_name="الموظف المصرّح",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="robot.robotdevice",
                        verbose_name="الجهاز",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="robot_scans",
                        to="inventory.product",
                        verbose_name="المنتج المطابق",
                    ),
                ),
                (
                    "sale_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="robot_scans",
                        to="inventory.saleinvoice",
                        verbose_name="فاتورة البيع",
                    ),
                ),
            ],
            options={
                "verbose_name": "مسح بصري",
                "verbose_name_plural": "📷 المسح البصري",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="robot_robot_created_e45ffb_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RobotAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("granted", "مصرّح"),
                            ("denied", "مرفوض"),
                            ("unknown", "وجه غير معروف"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("clock_in", "تسجيل حضور"),
                            ("clock_out", "تسجيل انصراف"),
                            ("authorize", "تفويض عملية"),
                            ("scan", "مسح فقط"),
                        ],
                        default="scan",
                        max_length=10,
                    ),
                ),
                (
                    "match_score",
                    models.FloatField(default=0.0, verbose_name="درجة التطابق"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="robot/faces/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="robot.robotdevice",
                        verbose_name="الجهاز",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="robot_access_logs",
                        to="hr.employee",
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل وصول (وجه)",
                "verbose_name_plural": "👤 سجلات الوصول (تعرّف الوجه)",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="robot_robot_created_00bf4e_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="procurementsignal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("product", "branch"),
                name="robot_one_open_procurement_signal_per_product_branch",
            ),
        ),
    ]
