# Generated by Django 4.2.30 on 2026-09-21 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0052_journalentry_branch"),
        ("hr", "0004_alter_aidesignsubscription_plan"),
        ("robot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="robotscanevent",
            name="created_new_product",
            field=models.BooleanField(default=False, verbose_name="منتج جديد؟"),
        ),
        migrations.AddField(
            model_name="robotscanevent",
            name="quantity_added",
            field=models.IntegerField(default=0, verbose_name="الكمية المضافة"),
        ),
        migrations.AlterField(
            model_name="robotscanevent",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("pos", "بيع (POS)"),
                    ("scrap", "تقييم مستعمل/خردة"),
                    ("lookup", "استعلام مخزون"),
                    ("intake", "إدخال بضاعة (تصوير + تسجيل)"),
                ],
                default="pos",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="RobotStockTakeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instruction",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="الأمر المنطوق",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "جاري"),
                            ("completed", "مكتمل"),
                            ("applied", "تم ترحيل التسويات"),
                            ("cancelled", "ملغي"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_takes",
                        to="robot.robotdevice",
                        verbose_name="الجهاز",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="robot_stock_takes",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة جرد",
                "verbose_name_plural": "📋 جلسات الجرد",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RobotStockTakeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_qty",
                    models.IntegerField(default=0, verbose_name="الكمية بالنظام"),
                ),
                (
                    "counted_qty",
                    models.IntegerField(default=0, verbose_name="الكمية المعدودة"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robot_stock_take_lines",
                        to="inventory.product",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="robot.robotstocktakesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "سطر جرد",
                "verbose_name_plural": "أسطر الجرد",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RobotKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_kind",
                    models.CharField(
                        choices=[
                            ("code", "رقم/كود مقروء"),
                            ("label", "اسم/وصف"),
                            ("fingerprint", "بصمة مرئية"),
                        ],
                        default="code",
                        max_length=12,
                    ),
                ),
                ("key_value", models.CharField(db_index=True, max_length=255)),
                (
                    "hit_count",
                    models.PositiveIntegerField(default=1, verbose_name="مرات التأكيد"),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="robot_confirmations",
                        to="hr.employee",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robot_knowledge",
                        to="inventory.product",
                        verbose_name="المنتج المؤكَّد",
                    ),
                ),
            ],
            options={
                "verbose_name": "معرفة الروبوت",
                "verbose_name_plural": "🧠 معرفة الروبوت (تعلّم)",
                "ordering": ["-hit_count", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["key_kind", "key_value"],
                        name="robot_robot_key_kin_75c08f_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="robotknowledge",
            constraint=models.UniqueConstraint(
                fields=("key_kind", "key_value", "product"),
                name="robot_knowledge_unique_key_product",
            ),
        ),
    ]
