# Generated by Django 4.2.30 on 2026-09-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0054_backfill_return_source_item"),
        ("robot", "0002_robotscanevent_created_new_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RobotCustomerFace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "face_encoding",
                    models.JSONField(blank=True, null=True, verbose_name="بصمة الوجه"),
                ),
                (
                    "visit_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد الزيارات"),
                ),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر زيارة"
                    ),
                ),
                ("notes", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robot_face",
                        to="inventory.customer",
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "ذاكرة عميل",
                "verbose_name_plural": "🙋 ذاكرة العملاء (تعرّف الوجه)",
                "ordering": ["-last_seen_at"],
            },
        ),
    ]
