# Generated by Django 4.2.30 on 2026-09-22 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_alter_aidesignsubscription_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("robot", "0003_robotcustomerface"),
    ]

    operations = [
        migrations.AddField(
            model_name="robotdevice",
            name="camera_always_on",
            field=models.BooleanField(
                default=True, verbose_name="الكاميرا تعمل ٢٤ ساعة"
            ),
        ),
        migrations.AddField(
            model_name="robotdevice",
            name="guard_from",
            field=models.TimeField(blank=True, null=True, verbose_name="بداية الحراسة"),
        ),
        migrations.AddField(
            model_name="robotdevice",
            name="guard_to",
            field=models.TimeField(blank=True, null=True, verbose_name="نهاية الحراسة"),
        ),
        migrations.AddField(
            model_name="robotdevice",
            name="last_frame",
            field=models.ImageField(
                blank=True, null=True, upload_to="robot/live/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="robotdevice",
            name="last_frame_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="robotdevice",
            name="last_motion_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="آخر حركة"),
        ),
        migrations.CreateModel(
            name="RobotSyncEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_uid", models.CharField(db_index=True, max_length=64)),
                ("kind", models.CharField(max_length=32)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("applied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_events",
                        to="robot.robotdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "حدث مزامنة",
                "verbose_name_plural": "🔄 أحداث المزامنة (أوفلاين)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RobotSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="robot/snapshots/%Y/%m/%d/")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("manual", "يدوي (من اللوحة)"),
                            ("motion", "حركة"),
                            ("after_hours", "حركة بعد الغلق"),
                            ("page", "مع نداء"),
                            ("scan", "مسح"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="robot.robotdevice",
                        verbose_name="الجهاز",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "لقطة",
                "verbose_name_plural": "📸 اللقطات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RobotPageCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="رسالة النداء",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار النداء"),
                            ("announced", "تم النداء"),
                            ("acknowledged", "ردّ الموظف"),
                            ("cancelled", "أُلغي"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("announced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="طلب النداء",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_calls",
                        to="robot.robotdevice",
                        verbose_name="الجهاز",
                    ),
                ),
                (
                    "target_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robot_pages",
                        to="hr.employee",
                        verbose_name="الموظف المطلوب",
                    ),
                ),
            ],
            options={
                "verbose_name": "نداء موظف",
                "verbose_name_plural": "📢 نداءات الموظفين",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RobotCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("snapshot", "التقط صورة"),
                            ("look_at", "لف الرأس تجاه"),
                            ("move", "تحرّك"),
                            ("say", "انطق نص"),
                            ("page", "نادِ على موظف"),
                            ("stream_start", "ابدأ البث"),
                            ("stream_stop", "أوقف البث"),
                        ],
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار"),
                            ("sent", "أُرسل للجهاز"),
                            ("done", "تم"),
                            ("failed", "فشل"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="robot.robotdevice",
                        verbose_name="الجهاز",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "أمر روبوت",
                "verbose_name_plural": "🎛️ أوامر الروبوت",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RobotAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("after_hours_motion", "حركة بعد غلق المحل"),
                            ("offline", "الروبوت فقد الاتصال"),
                            ("back_online", "الروبوت رجع أونلاين"),
                            ("other", "أخرى"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(blank=True, default="", max_length=255)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="robot.robotdevice",
                        verbose_name="الجهاز",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="robot.robotsnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنبيه روبوت",
                "verbose_name_plural": "🚨 تنبيهات الروبوت",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="robotsyncevent",
            constraint=models.UniqueConstraint(
                fields=("device", "client_uid"),
                name="robot_sync_unique_client_uid_per_device",
            ),
        ),
        migrations.AddIndex(
            model_name="robotcommand",
            index=models.Index(
                fields=["device", "status"], name="robot_robot_device__8eed0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="robotalert",
            index=models.Index(
                fields=["is_read", "-created_at"], name="robot_robot_is_read_6ab461_idx"
            ),
        ),
    ]
