# Generated by Django 4.2.30 on 2026-09-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0004_robotdevice_camera_always_on_robotdevice_guard_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="robotdevice",
            name="battery_percent",
            field=models.IntegerField(blank=True, null=True, verbose_name="البطارية %"),
        ),
        migrations.AddField(
            model_name="robotdevice",
            name="cpu_temp",
            field=models.FloatField(
                blank=True, null=True, verbose_name="حرارة المعالج"
            ),
        ),
        migrations.AddField(
            model_name="robotdevice",
            name="free_disk_mb",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="مساحة SD المتاحة (م.ب)"
            ),
        ),
        migrations.AddField(
            model_name="robotdevice",
            name="stream_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="robotdevice",
            name="telemetry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="robotdevice",
            name="wifi_rssi",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="قوة الواي فاي (dBm)"
            ),
        ),
        migrations.AlterField(
            model_name="robotalert",
            name="kind",
            field=models.CharField(
                choices=[
                    ("after_hours_motion", "حركة بعد غلق المحل"),
                    ("offline", "الروبوت فقد الاتصال"),
                    ("back_online", "الروبوت رجع أونلاين"),
                    ("low_battery", "بطارية منخفضة"),
                    ("other", "أخرى"),
                ],
                db_index=True,
                default="other",
                max_length=20,
            ),
        ),
    ]
