# Generated by Django 4.2.30 on 2026-09-23 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("robot", "0005_robotdevice_battery_percent_robotdevice_cpu_temp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="robotdevice",
            name="motor_health",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="صحة المواتير"
            ),
        ),
        migrations.AddField(
            model_name="robotdevice",
            name="shelf_map",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="خريطة الرفوف"
            ),
        ),
        migrations.AlterField(
            model_name="robotalert",
            name="kind",
            field=models.CharField(
                choices=[
                    ("after_hours_motion", "حركة بعد غلق المحل"),
                    ("offline", "الروبوت فقد الاتصال"),
                    ("back_online", "الروبوت رجع أونلاين"),
                    ("low_battery", "بطارية منخفضة"),
                    ("motor_fault", "مشكلة في موتور"),
                    ("other", "أخرى"),
                ],
                db_index=True,
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="robotcommand",
            name="kind",
            field=models.CharField(
                choices=[
                    ("snapshot", "التقط صورة"),
                    ("look_at", "لف الرأس تجاه"),
                    ("move", "تحرّك"),
                    ("say", "انطق نص"),
                    ("page", "نادِ على موظف"),
                    ("stream_start", "ابدأ البث"),
                    ("stream_stop", "أوقف البث"),
                    ("scan", "امسح القطعة قدام الكاميرا"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="robotsnapshot",
            name="reason",
            field=models.CharField(
                choices=[
                    ("manual", "يدوي (من اللوحة)"),
                    ("motion", "حركة"),
                    ("after_hours", "حركة بعد الغلق"),
                    ("page", "مع نداء"),
                    ("scan", "مسح"),
                    ("enroll", "تسجيل بصمة وجه"),
                ],
                default="manual",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="RobotFaceEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "جاري"),
                            ("done", "انتهى"),
                            ("cancelled", "أُلغي"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("entries", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_enrollments",
                        to="robot.robotdevice",
                        verbose_name="الجهاز",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة تسجيل بصمات الوجه",
                "verbose_name_plural": "🧑\u200d💼 جلسات تسجيل بصمات الوجه",
                "ordering": ["-created_at"],
            },
        ),
    ]
