# Generated by Django 4.2.30 on 2026-09-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0007_hash_device_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="robotdevice",
            name="listening_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="robotdevice",
            name="wake_aliases",
            field=models.JSONField(
                blank=True, default=list, verbose_name="طرق كتابة تانية للاسم"
            ),
        ),
        migrations.AddField(
            model_name="robotdevice",
            name="wake_name",
            field=models.CharField(
                default="موس", max_length=40, verbose_name="اسم الروبوت (للنداء)"
            ),
        ),
        migrations.AddField(
            model_name="robotdevice",
            name="wake_required",
            field=models.BooleanField(
                default=True, verbose_name="يرد بس لما يتنادى باسمه"
            ),
        ),
    ]
