# Generated by Django 4.2.30 on 2026-10-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_alter_aidesignsubscription_plan"),
        ("inventory", "0056_arabic_names_cogs_label"),
        ("robot", "0008_robot_wake_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RobotEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sale", "فاتورة بيع"),
                            ("purchase", "فاتورة شراء"),
                            ("expense", "مصروف"),
                        ],
                        max_length=10,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "مستني الفرع"),
                            ("done", "اتسجلت"),
                            ("cancelled", "اتلغت"),
                            ("failed", "فشلت"),
                            ("expired", "انتهى وقتها"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "summary",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="البيان"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="ملاحظة"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="robot_entries",
                        to="inventory.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="robot.robotdevice",
                        verbose_name="الجهاز",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="robot_entries",
                        to="hr.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "purchase_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.purchaseinvoice",
                    ),
                ),
                (
                    "sale_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.saleinvoice",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.financialtransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية مالية من الروبوت",
                "verbose_name_plural": "🧾 عمليات الروبوت المالية",
                "ordering": ["-created_at"],
            },
        ),
    ]
