# Generated by Django 4.2.30 on 2026-06-03 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VINDecodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17, unique=True)),
                ('decoded_data', models.JSONField(verbose_name='بيانات الـ VIN المفكوكة')),
                ('make', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('model_year', models.IntegerField(blank=True, null=True)),
                ('engine', models.CharField(blank=True, max_length=120)),
                ('provider', models.CharField(default='nhtsa', max_length=30)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'VIN decode cache',
                'verbose_name_plural': '🔐 VIN Decode Cache',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='DTCExternalLookupCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtc_code', models.CharField(db_index=True, max_length=8)),
                ('vehicle_signature', models.CharField(blank=True, db_index=True, help_text="e.g. 'BMW|F30|2015|N20' — to differentiate same DTC across vehicles", max_length=120)),
                ('provider', models.CharField(default='carmd', max_length=30)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'DTC external lookup cache',
                'verbose_name_plural': '🔐 DTC External Cache',
                'ordering': ['-fetched_at'],
                'unique_together': {('dtc_code', 'vehicle_signature', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='DTCDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='e.g. P0301, U0100', max_length=8, unique=True, verbose_name='DTC Code')),
                ('system', models.CharField(choices=[('P', 'Powertrain (P)'), ('C', 'Chassis (C)'), ('B', 'Body (B)'), ('U', 'Network/Comms (U)')], default='P', max_length=1)),
                ('short_description', models.CharField(max_length=200, verbose_name='الوصف المختصر')),
                ('full_description', models.TextField(blank=True, verbose_name='الوصف التفصيلي')),
                ('severity', models.CharField(choices=[('info', 'معلوماتي'), ('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'حرج'), ('critical', 'فوري — أوقف السيارة')], default='medium', max_length=10)),
                ('guided_steps', models.JSONField(blank=True, default=list, verbose_name='خطوات الفحص الموجَّه')),
                ('likely_oem_parts', models.JSONField(blank=True, default=list, help_text='قائمة OEM part numbers محتمل ارتباطها بالعطل', verbose_name='OEM parts المرجحة')),
                ('source', models.CharField(default='community', help_text='community | carmd | manual', max_length=30)),
                ('is_generic', models.BooleanField(default=True, help_text='True = OBD2 generic؛ False = manufacturer-specific')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تعريف كود عطل (DTC)',
                'verbose_name_plural': '📚 DTC Catalog — مرجع الأكواد',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['system', 'severity'], name='diagnostics_system_39616e_idx')],
            },
        ),
        migrations.CreateModel(
            name='APICostRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('endpoint', models.CharField(help_text="e.g. 'dtc_lookup', 'vin_decode'", max_length=80)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'سعر مكالمة API',
                'verbose_name_plural': '💵 API Cost Rates',
                'ordering': ['provider', 'endpoint'],
                'unique_together': {('provider', 'endpoint')},
            },
        ),
    ]
