# Generated by Django 4.2.30 on 2026-06-12 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_catalog', '0005_add_guided_steps_for_common_dtcs'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleProtocolMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, db_index=True, default='', help_text='اختياري — لو VIN متاح بنستخدمه كمفتاح أساسي.', max_length=17)),
                ('dongle_id', models.CharField(blank=True, db_index=True, default='', help_text='MAC الـ Bluetooth أو IP الـ WiFi — fallback لو VIN مش موجود.', max_length=64)),
                ('protocol_code', models.CharField(choices=[('1', 'SAE J1850 PWM'), ('2', 'SAE J1850 VPW'), ('3', 'ISO 9141-2 (K-Line)'), ('4', 'KWP2000 5-baud init'), ('5', 'KWP2000 fast init'), ('6', 'CAN 11-bit / 500 kbps'), ('7', 'CAN 29-bit / 500 kbps'), ('8', 'CAN 11-bit / 250 kbps'), ('9', 'CAN 29-bit / 250 kbps'), ('A', 'auto-search'), ('B', 'SAE J1939 (heavy-duty CAN)')], help_text='الكود اللي بيتبعت لـ ATSP — 1..9, A, B.', max_length=1)),
                ('protocol_label', models.CharField(blank=True, max_length=80)),
                ('sweep_seconds_saved', models.FloatField(default=0, help_text='تقدير الزمن المُوفَّر بإعادة استخدام البروتوكول المحفوظ.')),
                ('hit_count', models.IntegerField(default=1, help_text='مرات إعادة استخدام البروتوكول دا.')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'ذاكرة بروتوكول عربية',
                'verbose_name_plural': '🧠 ذاكرة البروتوكولات',
                'ordering': ['-last_used'],
                'indexes': [models.Index(fields=['vin'], name='vpm_vin_idx'), models.Index(fields=['dongle_id'], name='vpm_dongle_idx'), models.Index(fields=['-last_used'], name='vpm_last_used_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vehicleprotocolmemory',
            constraint=models.CheckConstraint(check=models.Q(('vin', ''), ('dongle_id', ''), _negated=True), name='vehicle_protocol_memory_has_identifier'),
        ),
    ]
