from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('omnichannel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAdsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscription_active', models.BooleanField(default=False, help_text='يتحكم في تشغيل النشر التلقائي والإعلانات لهذا المستأجر.', verbose_name='اشتراك استوديو التسويق فعّال؟')),
                ('subscription_started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء الاشتراك')),
                ('subscription_expires_at', models.DateTimeField(blank=True, help_text='اتركه فارغاً مع تفعيل الاشتراك للوصول مدى الحياة.', null=True, verbose_name='تاريخ انتهاء الاشتراك')),
                ('_page_access_token', models.TextField(blank=True, db_column='page_access_token_enc', default='', help_text='توكن صفحة فيسبوك — يُستخدم للنشر وقراءة الإحصاءات.', verbose_name='Page Access Token (مشفّر)')),
                ('_app_secret', models.TextField(blank=True, db_column='app_secret_enc', default='', verbose_name='Meta App Secret (مشفّر)')),
                ('facebook_page_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Facebook Page ID')),
                ('instagram_account_id', models.CharField(blank=True, db_index=True, default='', help_text='حساب إنستجرام الاحترافي المرتبط بالصفحة — للنشر على إنستجرام.', max_length=64, verbose_name='Instagram Business Account ID')),
                ('ad_account_id', models.CharField(blank=True, default='', help_text='حساب الإعلانات — تُخصم تكلفة الإعلانات من وسيلة الدفع المربوطة به لدى Meta.', max_length=64, verbose_name='Meta Ad Account ID (act_...)')),
                ('facebook_enabled', models.BooleanField(default=True, verbose_name='النشر على فيسبوك مفعّل؟')),
                ('instagram_enabled', models.BooleanField(default=True, verbose_name='النشر على إنستجرام مفعّل؟')),
                ('ads_enabled', models.BooleanField(default=False, help_text='عند التفعيل يستطيع البوت إنشاء حملات مدفوعة ضمن حدود الميزانية أدناه.', verbose_name='إنشاء الحملات الإعلانية مفعّل؟')),
                ('business_display_name', models.CharField(blank=True, default='', max_length=120, verbose_name='اسم النشاط التجاري')),
                ('industry', models.CharField(blank=True, default='', help_text='مثال: قطع غيار سيارات، مطبعة، مطعم، عيادة أسنان...', max_length=120, verbose_name='مجال النشاط')),
                ('products_services', models.TextField(blank=True, default='', help_text='اكتب أهم ما تبيعه — يبني عليه البوت أفكار البوستات والإعلانات.', verbose_name='المنتجات / الخدمات الرئيسية')),
                ('target_audience', models.TextField(blank=True, default='', help_text='مثال: أصحاب السيارات في القاهرة، من 25 لـ 45 سنة، مهتمين بالصيانة.', verbose_name='الجمهور المستهدف')),
                ('brand_tone', models.CharField(blank=True, default='عصري، ودود، وواثق — يلفت الانتباه ويشجّع على التفاعل.', max_length=255, verbose_name='نبرة العلامة التجارية')),
                ('brand_keywords', models.CharField(blank=True, default='', help_text='افصل بينها بفواصل — يعطيها البوت أولوية في الهاشتاجات.', max_length=255, verbose_name='كلمات مفتاحية / هاشتاجات مميّزة')),
                ('business_goals', models.CharField(blank=True, default='زيادة الوعي بالعلامة وجذب عملاء جدد.', max_length=255, verbose_name='أهداف التسويق')),
                ('call_to_action', models.CharField(blank=True, default='تواصل معنا الآن عبر الرسائل أو الاتصال.', max_length=160, verbose_name='الدعوة لاتخاذ إجراء (CTA) الافتراضية')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='رقم التواصل في البوستات')),
                ('website_url', models.URLField(blank=True, default='', verbose_name='رابط الموقع / المتجر')),
                ('banned_words', models.CharField(blank=True, default='', help_text='كلمات لا يستخدمها البوت إطلاقاً — افصل بينها بفواصل.', max_length=255, verbose_name='عبارات ممنوعة')),
                ('autopilot_mode', models.CharField(choices=[('off', 'إيقاف — أنا أراجع كل بوست يدوياً'), ('suggest', 'اقتراح — يجهّز مسودات وأنا أعتمدها'), ('full', 'تلقائي كامل — يكتب ويجدول وينشر وحده')], default='suggest', max_length=8, verbose_name='وضع الطيار الآلي')),
                ('posts_per_week', models.PositiveSmallIntegerField(default=5, help_text='كم بوست يجهّزه البوت ويجدوله كل أسبوع (1–21).', verbose_name='عدد البوستات أسبوعياً')),
                ('preferred_times', models.CharField(blank=True, default='11:00,19:00', help_text='مواعيد باليوم (24h) مفصولة بفواصل — يبدأ البوت بها ثم يحسّنها بالتعلّم.', max_length=120, verbose_name='أوقات النشر المفضّلة')),
                ('default_language', models.CharField(choices=[('ar', 'عربي'), ('en', 'إنجليزي'), ('mix', 'عربي + إنجليزي')], default='ar', max_length=8, verbose_name='لغة المحتوى')),
                ('generate_images', models.BooleanField(default=True, help_text='يقترح البوت وصفاً بصرياً ويولّد صورة لكل بوست (حسب مزوّد الصور).', verbose_name='توليد صور للبوستات؟')),
                ('monthly_ad_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='لن يتجاوز البوت هذا الحد في الحملات المدفوعة (بعملة حساب إعلاناتك).', max_digits=10, verbose_name='سقف الإنفاق الإعلاني الشهري')),
                ('max_daily_ad_budget', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10, verbose_name='أقصى ميزانية يومية للحملة الواحدة')),
                ('auto_optimize_ads', models.BooleanField(default=True, help_text='يعيد توزيع الميزانية نحو الإعلانات الأفضل أداءً ويوقف الضعيفة.', verbose_name='تحسين الحملات تلقائياً؟')),
                ('llm_provider', models.CharField(choices=[('platform', 'Mouss Tec (Gemini) — مزوّد المنصة'), ('openai', 'OpenAI (مفتاح الشركة)'), ('gemini', 'Google Gemini (مفتاح الشركة)')], default='platform', max_length=16, verbose_name='مزوّد الذكاء الاصطناعي')),
                ('_llm_api_key', models.TextField(blank=True, db_column='llm_api_key_enc', default='', verbose_name='مفتاح LLM (مشفّر)')),
                ('llm_model', models.CharField(blank=True, default='', max_length=80, verbose_name='موديل الـ LLM')),
                ('notify_email', models.EmailField(blank=True, default='', help_text='يصله تقرير أسبوعي وتنبيه عند فشل نشر أو حاجة اعتماد مسودة.', max_length=254, verbose_name='بريد التنبيهات')),
                ('notify_on_publish', models.BooleanField(default=False, verbose_name='إشعار عند كل نشر؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_ads_config', to='clients.client', verbose_name='الشركة (المستأجر)')),
            ],
            options={
                'verbose_name': 'إعدادات استوديو التسويق',
                'verbose_name_plural': '📣 إعدادات استوديو التسويق (Social Studio)',
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('both', 'فيسبوك + إنستجرام')], default='both', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'مسودة — بانتظار الاعتماد'), ('scheduled', 'مجدول'), ('publishing', 'جارٍ النشر'), ('published', 'منشور'), ('failed', 'فشل النشر'), ('cancelled', 'ملغى')], db_index=True, default='draft', max_length=12)),
                ('source', models.CharField(choices=[('autopilot', 'طيار آلي'), ('manual', 'يدوي')], default='autopilot', max_length=12)),
                ('title', models.CharField(blank=True, default='', max_length=180, verbose_name='عنوان داخلي')),
                ('caption', models.TextField(verbose_name='نص البوست')),
                ('hashtags', models.CharField(blank=True, default='', max_length=400, verbose_name='الهاشتاجات')),
                ('image_prompt', models.TextField(blank=True, default='', verbose_name='وصف الصورة (Prompt)')),
                ('image_url', models.URLField(blank=True, default='', max_length=600, verbose_name='رابط الصورة')),
                ('strategy_angle', models.CharField(blank=True, db_index=True, default='', help_text='مثال: عرض_سعري، نصيحة، شهادة_عميل، خلف_الكواليس، سؤال_تفاعلي.', max_length=80, verbose_name='زاوية المحتوى')),
                ('ai_rationale', models.TextField(blank=True, default='', verbose_name='لماذا اقترح البوت هذا؟')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='موعد النشر')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت النشر الفعلي')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('fb_post_id', models.CharField(blank=True, default='', max_length=128)),
                ('ig_media_id', models.CharField(blank=True, default='', max_length=128)),
                ('permalink', models.URLField(blank=True, default='', max_length=600)),
                ('error', models.TextField(blank=True, default='')),
                ('publish_attempts', models.PositiveSmallIntegerField(default=0)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0, help_text='(تفاعلات / وصول) %')),
                ('insights_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social_ads.socialadsconfig')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='clients.client')),
            ],
            options={
                'verbose_name': 'بوست اجتماعي',
                'verbose_name_plural': 'بوستات اجتماعية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='اسم الحملة')),
                ('objective', models.CharField(choices=[('OUTCOME_AWARENESS', 'الوعي بالعلامة'), ('OUTCOME_TRAFFIC', 'زيارات / نقرات'), ('OUTCOME_ENGAGEMENT', 'تفاعل'), ('OUTCOME_LEADS', 'جذب عملاء محتملين'), ('OUTCOME_SALES', 'مبيعات')], default='OUTCOME_TRAFFIC', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'بانتظار الاعتماد'), ('active', 'نشطة'), ('paused', 'موقوفة'), ('completed', 'مكتملة'), ('failed', 'فشل الإنشاء')], db_index=True, default='draft', max_length=12)),
                ('source', models.CharField(default='autopilot', max_length=12)),
                ('primary_text', models.TextField(blank=True, default='', verbose_name='نص الإعلان')),
                ('headline', models.CharField(blank=True, default='', max_length=200, verbose_name='العنوان الرئيسي')),
                ('audience_spec', models.JSONField(blank=True, default=dict, verbose_name='مواصفات الجمهور')),
                ('daily_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('duration_days', models.PositiveSmallIntegerField(default=7)),
                ('meta_campaign_id', models.CharField(blank=True, default='', max_length=64)),
                ('meta_adset_id', models.CharField(blank=True, default='', max_length=64)),
                ('meta_ad_id', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('results', models.PositiveIntegerField(default=0, help_text='نتائج حسب الهدف (رسائل/زيارات/عملاء).')),
                ('cost_per_result', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('insights_synced_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='social_ads.socialadsconfig')),
                ('post', models.ForeignKey(blank=True, help_text='البوست المُروَّج (إن وجد).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='social_ads.socialpost')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='clients.client')),
            ],
            options={
                'verbose_name': 'حملة إعلانية',
                'verbose_name_plural': 'حملات إعلانية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle_scores', models.JSONField(blank=True, default=dict, verbose_name='أداء زوايا المحتوى')),
                ('best_hours', models.JSONField(blank=True, default=list, verbose_name='أفضل ساعات النشر')),
                ('top_hashtags', models.JSONField(blank=True, default=list, verbose_name='أفضل الهاشتاجات')),
                ('winning_examples', models.JSONField(blank=True, default=list, verbose_name='نماذج ناجحة')),
                ('learned_brief', models.TextField(blank=True, default='', verbose_name='خلاصة ما تعلّمه البوت')),
                ('posts_analyzed', models.PositiveIntegerField(default=0)),
                ('avg_engagement_rate', models.FloatField(default=0.0)),
                ('last_learned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='social_ads.socialadsconfig')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_memory', to='clients.client')),
            ],
            options={
                'verbose_name': 'ذاكرة استراتيجية',
                'verbose_name_plural': 'ذواكر استراتيجية',
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('post', 'بوست'), ('campaign', 'حملة')], max_length=10)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('interactions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('results', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='social_ads.adcampaign')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='social_ads.socialpost')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_snapshots', to='clients.client')),
            ],
            options={
                'verbose_name': 'لقطة أداء',
                'verbose_name_plural': 'لقطات أداء',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['status', 'scheduled_at'], name='socialads_due_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['tenant', '-created_at'], name='socialads_tenant_idx'),
        ),
    ]
