# Generated by Django 4.2.30 on 2026-05-28 14:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDesignSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'أساسي — 50 تصميم AI شهرياً'), ('pro', 'احترافي — 200 تصميم AI شهرياً'), ('unlimited', 'غير محدود — تصاميم لا نهائية')], default='basic', max_length=15, verbose_name='الباقة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('cancelled', 'ملغي'), ('pending_payment', 'في انتظار الدفع')], default='pending_payment', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('auto_renew', models.BooleanField(default=False, help_text='عند التفعيل: يتجدد الاشتراك تلقائياً عند انتهائه (يتطلب بطاقة محفوظة)', verbose_name='تجديد تلقائي')),
                ('payment_method', models.CharField(choices=[('visa', 'فيزا / بطاقة ائتمان'), ('admin_manual', 'تفعيل يدوي من الأدمن'), ('wallet', 'خصم من رصيد الشركة')], default='visa', max_length=15, verbose_name='طريقة الدفع')),
                ('price_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='المبلغ المدفوع')),
                ('payment_reference', models.CharField(blank=True, help_text='رقم العملية من بوابة الدفع أو ملاحظة التفعيل اليدوي', max_length=200, verbose_name='مرجع الدفع')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='آخر 4 أرقام من البطاقة')),
                ('ai_generations_used', models.PositiveIntegerField(default=0, verbose_name='عدد التصاميم المُنشأة بالـ AI')),
                ('ai_generations_limit', models.PositiveIntegerField(default=50, help_text='0 يعني غير محدود', verbose_name='الحد الأقصى للتصاميم')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الأدمن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_subs_activated', to=settings.AUTH_USER_MODEL, verbose_name='فعّله')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_subs_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='ألغاه')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_subscriptions', to='hr.employee', verbose_name='المصمم')),
            ],
            options={
                'verbose_name': 'اشتراك AI تصميم',
                'verbose_name_plural': 'اشتراكات AI التصميم',
                'ordering': ['-created_at'],
            },
        ),
    ]
