# Generated by Django 4.2.30 on 2026-05-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_hrsettings_attendance_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidesignsubscription',
            name='plan',
            field=models.CharField(choices=[('basic', 'أساسي — 100 تصميم AI شهرياً'), ('pro', 'احترافي — 300 تصميم AI شهرياً'), ('unlimited', 'غير محدود — تصاميم لا نهائية')], default='basic', max_length=15, verbose_name='الباقة'),
        ),
    ]
