# Generated by Django 4.2.30 on 2026-05-13 18:48

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, verbose_name='اسم المركز/الشركة')),
                ('owner_name', models.CharField(max_length=100, verbose_name='اسم المالك')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('plan', models.CharField(choices=[('basic', 'باقة أساسية (900 ج.م)'), ('pro', 'باقة المحترفين (1500 ج.م)'), ('enterprise', 'باقة الشركات (3000 ج.م)')], default='basic', max_length=20, verbose_name='الباقة')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='الاشتراك فعال؟')),
            ],
            options={
                'verbose_name': 'مركز صيانة (عميل)',
                'verbose_name_plural': 'مراكز الصيانة (العملاء)',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='clients.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
