# Generated by Django 4.2.30 on 2026-05-16 15:20

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'مركز صيانة (عميل SaaS)', 'verbose_name_plural': 'مراكز الصيانة (عملاء المنصة)'},
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني للإدارة'),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/', verbose_name='لوجو المركز'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_branches',
            field=models.IntegerField(default=1, verbose_name='الحد الأقصى للفروع'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_users',
            field=models.IntegerField(default=3, verbose_name='الحد الأقصى للمستخدمين'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('trial', 'فترة تجريبية'), ('active', 'نشط (مدفوع)'), ('suspended', 'معلق (لعدم الدفع)'), ('cancelled', 'ملغي (محذوف سوفت)')], default='trial', max_length=20, verbose_name='حالة الحساب'),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الاشتراك'),
        ),
        migrations.AddField(
            model_name='client',
            name='theme_color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='اللون الأساسي للسيستم (Hex)'),
        ),
        migrations.AddField(
            model_name='client',
            name='trial_ends_at',
            field=models.DateField(default=clients.models.default_trial_end, verbose_name='نهاية الفترة التجريبية'),
        ),
        migrations.AlterField(
            model_name='client',
            name='plan',
            field=models.CharField(choices=[('basic', 'باقة أساسية (فرع واحد - 3 مستخدمين)'), ('pro', 'باقة المحترفين (3 فروع - 10 مستخدمين)'), ('enterprise', 'باقة الشركات (فروع ومستخدمين غير محدود)')], default='basic', max_length=20, verbose_name='الباقة'),
        ),
    ]
