# Generated by Django 4.2.30 on 2026-05-17 11:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_client_email_client_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'شركة / مركز (عميل SaaS)', 'verbose_name_plural': 'شركات Mouss Tec Ecosystem'},
        ),
        migrations.AddField(
            model_name='client',
            name='business_type',
            field=models.CharField(choices=[('service_center', 'مركز صيانة متكامل (ورشة + قطع غيار)'), ('parts_dealer', 'تاجر قطع غيار (مبيعات تجزئة وجملة)'), ('scrap_importer', 'مستورد تقطيع وأنصاف (محرك الـ Scrap)'), ('both', 'توكيل شامل (صيانة + تجارة + استيراد)')], default='service_center', max_length=20, verbose_name='نوع النشاط'),
        ),
        migrations.AddField(
            model_name='client',
            name='commercial_register',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='السجل التجاري'),
        ),
        migrations.AddField(
            model_name='client',
            name='escrow_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='رصيد محفظة الضمان (Escrow)'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_marketplace_active',
            field=models.BooleanField(default=True, verbose_name='مشارك في سوق التجار (B2B)؟'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_verified_merchant',
            field=models.BooleanField(default=False, verbose_name='تاجر موثق (علامة زرقاء)'),
        ),
        migrations.AddField(
            model_name='client',
            name='market_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='تقييم التاجر/المركز'),
        ),
        migrations.AlterField(
            model_name='client',
            name='theme_color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='اللون الأساسي للسيستم'),
        ),
        migrations.CreateModel(
            name='BlindBiddingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('part_number', models.CharField(max_length=100, verbose_name='القطعة المطلوبة')),
                ('required_qty', models.IntegerField(default=1, verbose_name='الكمية المطلوبة')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر المستهدف (مخفي)')),
                ('winning_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الترسية')),
                ('status', models.CharField(choices=[('open', 'مفتوح لتلقي العروض'), ('escrow_held', 'تم الترسية (الفلوس في الضمان)'), ('shipped', 'تم الشحن / جاري الاستلام'), ('completed', 'مكتمل (تم تحويل الأموال للتاجر)'), ('disputed', 'متنازع عليه (صورة غير مطابقة)'), ('cancelled', 'ملغي')], default='open', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='ينتهي العطاء في')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_created', to='clients.client', verbose_name='المركز الطالب')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids_won', to='clients.client', verbose_name='التاجر الفائز')),
            ],
            options={
                'verbose_name': 'طلب شراء / مزاد عكسي',
                'verbose_name_plural': '⚖️ مزادات الـ Blind Bidding',
            },
        ),
        migrations.CreateModel(
            name='GlobalB2BMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(db_index=True, max_length=100, verbose_name='رقم القطعة (P/N)')),
                ('product_name', models.CharField(max_length=200, verbose_name='اسم القطعة')),
                ('brand', models.CharField(default='BMW', max_length=100, verbose_name='الماركة')),
                ('condition', models.CharField(choices=[('new', 'جديد (أصلي/بديل)'), ('used', 'استيراد / تقطيع'), ('core', 'تالف قابل للتجديد (Core)')], default='new', max_length=20, verbose_name='الحالة')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الجملة للمراكز')),
                ('available_qty', models.IntegerField(default=0, verbose_name='الكمية المتاحة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث للمخزون')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_products', to='clients.client', verbose_name='التاجر')),
            ],
            options={
                'verbose_name': 'صنف في السوق المركزي',
                'verbose_name_plural': '🛒 سوق التجار المركزي (Marketplace)',
                'unique_together': {('tenant', 'part_number', 'condition')},
            },
        ),
    ]
