# Generated by Django 4.2.30 on 2026-05-17 14:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_options_client_business_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalb2bmarketplace',
            options={'verbose_name': 'صنف في السوق المركزي', 'verbose_name_plural': '🛒 سوق التجار المركزي'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='escrow_balance',
        ),
        migrations.AddField(
            model_name='blindbiddingrequest',
            name='auto_award',
            field=models.BooleanField(default=False, verbose_name='ترسية آلية لأفضل عرض؟'),
        ),
        migrations.AddField(
            model_name='blindbiddingrequest',
            name='platform_fee_collected',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='عمولة المنصة المحصلة'),
        ),
        migrations.AddField(
            model_name='client',
            name='dispute_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة النزاعات (%)'),
        ),
        migrations.AddField(
            model_name='client',
            name='escrow_held',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='رصيد مجمد في الضمان (Escrow)'),
        ),
        migrations.AddField(
            model_name='client',
            name='platform_fee_rate',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='عمولة Mouss Tec (%)'),
        ),
        migrations.AddField(
            model_name='client',
            name='successful_deals',
            field=models.IntegerField(default=0, verbose_name='الصفقات الناجحة'),
        ),
        migrations.AddField(
            model_name='client',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الرصيد المتاح للسحب'),
        ),
        migrations.AddField(
            model_name='globalb2bmarketplace',
            name='ai_quality_confidence',
            field=models.IntegerField(default=95, help_text='مؤشر ذكاء اصطناعي من 1 لـ 100 لجودة هذا الصنف من هذا التاجر'),
        ),
        migrations.AlterField(
            model_name='blindbiddingrequest',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح لتلقي العروض'), ('awarding', 'جاري الترسية الآلية'), ('escrow_held', 'تم الترسية (الفلوس في الضمان)'), ('shipped', 'تم الشحن / جاري الاستلام'), ('completed', 'مكتمل (تم تحويل الأموال للتاجر)'), ('disputed', 'متنازع عليه (صورة غير مطابقة)'), ('cancelled', 'ملغي')], default='open', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='client',
            name='market_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='التقييم العام'),
        ),
        migrations.CreateModel(
            name='EscrowLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'إيداع في المحفظة'), ('hold', 'تجميد أموال (دخول مزاد)'), ('release', 'تحرير أموال (استلام البضاعة)'), ('refund', 'استرداد أموال (إلغاء/نزاع)'), ('fee_deduction', 'خصم عمولة المنصة'), ('withdrawal', 'سحب للأرباح خارج المنصة')], max_length=20, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bidding_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.blindbiddingrequest', verbose_name='مرتبط بمزاد')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='clients.client', verbose_name='الشركة/المركز')),
            ],
            options={
                'verbose_name': 'حركة مالية (Escrow)',
                'verbose_name_plural': '🏦 دفتر الأستاذ المالي (Ledger)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر العرض')),
                ('condition', models.CharField(choices=[('new', 'جديد (أصلي/بديل)'), ('used', 'استيراد / تقطيع'), ('core', 'تالف قابل للتجديد (Core)')], default='new', max_length=20, verbose_name='حالة القطعة المعروضة')),
                ('estimated_delivery_days', models.IntegerField(default=1, verbose_name='أيام التوصيل المتوقعة')),
                ('is_winner', models.BooleanField(default=False, verbose_name='هل هو العرض الفائز؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidding_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='clients.blindbiddingrequest', verbose_name='طلب المزاد')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to='clients.client', verbose_name='التاجر مقدم العرض')),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض أسعار التجار',
                'unique_together': {('bidding_request', 'seller')},
            },
        ),
    ]
