# Generated by Django 4.2.30 on 2026-05-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_industry_update_business_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAddonPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='اسم الحزمة')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الشهري (ج.م)')),
                ('ai_generations_limit', models.IntegerField(default=0, verbose_name='حد التوليد بالذكاء الاصطناعي')),
                ('whatsapp_messages_limit', models.IntegerField(default=0, verbose_name='حد رسائل واتساب')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='مميزات الحزمة')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'حزمة AI إضافية',
                'verbose_name_plural': '🤖 حزم AI Studio',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='المعرف')),
                ('name', models.CharField(max_length=80, verbose_name='اسم الباقة')),
                ('industry', models.CharField(choices=[('automotive', 'سيارات'), ('printing', 'طباعة وتصميم')], max_length=20, verbose_name='القطاع')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الشهري (ج.م)')),
                ('quarterly_discount', models.IntegerField(default=10, verbose_name='خصم ربع سنوي (%)')),
                ('semi_annual_discount', models.IntegerField(default=15, verbose_name='خصم نصف سنوي (%)')),
                ('annual_discount', models.IntegerField(default=20, verbose_name='خصم سنوي (%)')),
                ('max_branches', models.IntegerField(default=1)),
                ('max_users', models.IntegerField(default=1)),
                ('max_treasuries', models.IntegerField(default=1)),
                ('features', models.JSONField(blank=True, default=list, verbose_name='المميزات')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'باقة اشتراك',
                'verbose_name_plural': '💎 باقات الاشتراك',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='extra_branches_purchased',
            field=models.IntegerField(default=0, verbose_name='فروع إضافية مشتراة'),
        ),
        migrations.AddField(
            model_name='client',
            name='extra_users_purchased',
            field=models.IntegerField(default=0, verbose_name='مستخدمين إضافيين مشتراة'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_fraud_flagged',
            field=models.BooleanField(default=False, verbose_name='مُحظر آلياً للاشتباه بالاحتيال'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_inventory_items',
            field=models.IntegerField(default=0, help_text='0 تعني غير محدود', verbose_name='حد أصناف المخزن'),
        ),
        migrations.AddField(
            model_name='client',
            name='max_repair_cards',
            field=models.IntegerField(default=0, help_text='0 تعني غير محدود', verbose_name='حد كروت الصيانة الشهري'),
        ),
        migrations.AlterField(
            model_name='client',
            name='max_branches',
            field=models.IntegerField(default=2, verbose_name='الفروع المشمولة بالباقة'),
        ),
        migrations.AlterField(
            model_name='client',
            name='max_users',
            field=models.IntegerField(default=5, verbose_name='المستخدمين المشمولين بالباقة'),
        ),
        migrations.AlterField(
            model_name='globalb2bmarketplace',
            name='ai_quality_confidence',
            field=models.IntegerField(default=95, help_text='مؤشر ذكاء اصطناعي لجودة هذا الصنف من هذا التاجر'),
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle_months', models.IntegerField(default=1, verbose_name='دورة الفوترة (أشهر)')),
                ('current_period_start', models.DateField(blank=True, null=True)),
                ('current_period_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.aiaddonpackage', verbose_name='حزمة AI')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.plan', verbose_name='الباقة')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clients.client', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'اشتراك مستأجر',
                'verbose_name_plural': '📋 اشتراكات المستأجرين',
            },
        ),
        migrations.CreateModel(
            name='AILimitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ai_generation', 'توليد صورة بالذكاء الاصطناعي'), ('whatsapp_send', 'إرسال رسالة واتساب'), ('smart_watermark', 'علامة مائية ذكية')], max_length=30, verbose_name='نوع العملية')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_log', to='clients.client', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'سجل استهلاك AI',
                'verbose_name_plural': '📊 سجل استهلاك AI Studio',
                'ordering': ['-used_at'],
            },
        ),
    ]
