# Generated by Django 4.2.30 on 2026-05-28 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0011_seed_plans_and_ai_addons'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('signup', 'تسجيل شركة جديدة'), ('login', 'تسجيل دخول'), ('payment', 'عملية دفع'), ('subscription', 'تفعيل اشتراك'), ('suspension', 'تعليق حساب'), ('fraud_flag', 'تعليم احتيال'), ('invoice', 'إنشاء فاتورة'), ('error', 'خطأ في النظام'), ('other', 'أخرى')], max_length=20)),
                ('tenant_schema', models.CharField(blank=True, db_index=True, max_length=100)),
                ('tenant_name', models.CharField(blank=True, max_length=150)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'حدث منصة',
                'verbose_name_plural': 'أحداث المنصة',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tenant_schema', models.CharField(blank=True, db_index=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True, max_length=1000)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل زائر',
                'verbose_name_plural': 'سجلات الزوار',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'tenant_schema'], name='clients_vis_timesta_d44fe8_idx'), models.Index(fields=['ip_address', '-timestamp'], name='clients_vis_ip_addr_34ae2f_idx')],
            },
        ),
    ]
