# Generated by Django 4.2.30 on 2026-05-29 01:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_add_visitor_log_platform_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_type', models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة / مؤسسة')], max_length=20, verbose_name='نوع العميل')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='رقم الموبايل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='الوظيفة / المسمى')),
                ('sector', models.CharField(choices=[('automotive', '🚗 سيارات — صيانة وقطع غيار'), ('printing', '🎨 طباعة وتصميم')], max_length=20, verbose_name='القطاع')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة / المحافظة')),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق من الموبايل')),
                ('session_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_accepted_offers', models.IntegerField(default=0)),
                ('avg_rating_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('is_blocked', models.BooleanField(default=False, verbose_name='محظور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عميل السوق',
                'verbose_name_plural': '🛍️ عملاء سوق المناقصات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sector', models.CharField(choices=[('automotive', '🚗 سيارات — صيانة وقطع غيار'), ('printing', '🎨 طباعة وتصميم')], max_length=20, verbose_name='القطاع')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان الطلب')),
                ('description', models.TextField(verbose_name='تفاصيل الطلب')),
                ('urgency', models.CharField(choices=[('normal', 'عادي — خلال أسبوع'), ('soon', 'قريب — خلال 3 أيام'), ('urgent', 'عاجل — خلال 24 ساعة')], default='normal', max_length=10, verbose_name='درجة الاستعجال')),
                ('wants_images', models.BooleanField(default=False, verbose_name='يريد صور مع العروض')),
                ('customer_city', models.CharField(blank=True, max_length=100, verbose_name='مدينة العميل')),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الميزانية القصوى (اختياري — مخفي عن التجار)')),
                ('attachment_1', models.ImageField(blank=True, null=True, upload_to='marketplace/requests/', verbose_name='صورة مرجعية 1')),
                ('attachment_2', models.ImageField(blank=True, null=True, upload_to='marketplace/requests/', verbose_name='صورة مرجعية 2')),
                ('status', models.CharField(choices=[('open', 'مفتوح — في انتظار العروض'), ('reviewing', 'جاري مراجعة العروض'), ('accepted', 'تم قبول عرض'), ('completed', 'مكتمل — تم التقييم'), ('expired', 'منتهي الصلاحية'), ('cancelled', 'ملغي بواسطة العميل')], db_index=True, default='open', max_length=20)),
                ('offers_count', models.IntegerField(default=0)),
                ('platform_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='عمولة المنصة (%)')),
                ('platform_commission_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(verbose_name='ينتهي الطلب في')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'طلب خدمة / مناقصة',
                'verbose_name_plural': '🛍️ طلبات سوق العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر المقترح')),
                ('description', models.TextField(verbose_name='تفاصيل العرض')),
                ('estimated_days', models.IntegerField(default=1, verbose_name='أيام التنفيذ المتوقعة')),
                ('warranty_days', models.IntegerField(default=0, verbose_name='مدة الضمان (أيام)')),
                ('merchant_city', models.CharField(max_length=100, verbose_name='مدينة التاجر')),
                ('merchant_address', models.CharField(blank=True, max_length=300, verbose_name='عنوان التاجر التفصيلي')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='marketplace/offers/', verbose_name='صورة 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='marketplace/offers/', verbose_name='صورة 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='marketplace/offers/', verbose_name='صورة 3')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='marketplace/offers/files/', verbose_name='ملف مرفق (PDF/Word)')),
                ('status', models.CharField(choices=[('pending', 'في انتظار مراجعة العميل'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('withdrawn', 'تم سحبه من التاجر')], db_index=True, default='pending', max_length=20)),
                ('customer_rating', models.IntegerField(blank=True, null=True, verbose_name='تقييم العميل (1-5)')),
                ('customer_review', models.TextField(blank=True, verbose_name='تعليق العميل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_offers', to='clients.client', verbose_name='التاجر')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='clients.servicerequest', verbose_name='طلب الخدمة')),
            ],
            options={
                'verbose_name': 'عرض سعر تاجر',
                'verbose_name_plural': 'عروض أسعار التجار',
                'ordering': ['price'],
                'unique_together': {('service_request', 'merchant')},
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='accepted_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for', to='clients.tenderoffer'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='clients.marketplacecustomer', verbose_name='العميل'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['sector', 'status', '-created_at'], name='clients_ser_sector_ab282f_idx'),
        ),
    ]
