# Generated by Django 4.2.30 on 2026-05-29 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0013_add_marketplace_customer_service_request_tender_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBonusGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_designs', models.IntegerField(default=0, verbose_name='تصاميم مهداه')),
                ('granted_whatsapp', models.IntegerField(default=0, verbose_name='رسائل واتساب مهداه')),
                ('granted_watermarks', models.IntegerField(default=0, verbose_name='علامات مائية مهداه')),
                ('consumed_designs', models.IntegerField(default=0)),
                ('consumed_whatsapp', models.IntegerField(default=0)),
                ('consumed_watermarks', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=250, verbose_name='سبب الهدية')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء (اختياري)')),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_bonus_grants', to='clients.client', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'هدية رصيد AI',
                'verbose_name_plural': '🎁 هدايا رصيد AI Studio',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='AIStudioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_input', models.TextField(verbose_name='النص الأصلي')),
                ('engineered_prompt', models.TextField(blank=True, verbose_name='البرومبت المحسّن')),
                ('negative_prompt', models.TextField(blank=True)),
                ('design_category', models.CharField(blank=True, max_length=50)),
                ('logo_used', models.BooleanField(default=False, verbose_name='استُخدم لوجو؟')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='ai_studio/logos/')),
                ('image_url', models.URLField(blank=True, max_length=600, verbose_name='رابط التصميم')),
                ('image_size', models.CharField(default='1024x1024', max_length=20)),
                ('image_quality', models.CharField(default='hd', max_length=20)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('watermarked', models.BooleanField(default=False, verbose_name='بعلامة مائية')),
                ('watermarked_image_url', models.URLField(blank=True, max_length=600)),
                ('sent_to_phone', models.CharField(blank=True, max_length=30)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='clients.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جلسة AI Studio',
                'verbose_name_plural': '💾 سجل جلسات AI Studio',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='clients_ais_tenant__701b78_idx')],
            },
        ),
    ]
