# Generated by Django 4.2.30 on 2026-05-29 15:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_add_ai_bonus_grant_and_studio_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('starter', '🥉 Starter — 25 تصميم'), ('pro', '🥈 Pro — 50 تصميم'), ('business', '🥇 Business — 100 تصميم'), ('studio', '💎 Studio — 250 تصميم')], max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربي')),
                ('designs_count', models.IntegerField(verbose_name='عدد التصاميم')),
                ('price_egp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر بالجنيه')),
                ('price_per_design', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('allows_logo_upload', models.BooleanField(default=True)),
                ('allows_watermark', models.BooleanField(default=False)),
                ('allows_source_files', models.BooleanField(default=False, verbose_name='ملفات مصدر (PSD/SVG)')),
                ('allows_commercial_use', models.BooleanField(default=True, verbose_name='استخدام تجاري')),
                ('allows_whatsapp_delivery', models.BooleanField(default=True)),
                ('free_regenerations_per_design', models.IntegerField(default=3, verbose_name='إعادة توليد مجاني')),
                ('resolution_max', models.CharField(default='2048x2048', max_length=20, verbose_name='أعلى دقة')),
                ('quality_level', models.CharField(choices=[('standard', 'عادية'), ('hd', 'عالية'), ('ultra', 'فائقة')], default='hd', max_length=20)),
                ('icon_emoji', models.CharField(default='🎨', max_length=10)),
                ('accent_color', models.CharField(default='#8b5cf6', max_length=7)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('description_html', models.TextField(blank=True, verbose_name='الوصف')),
                ('badge_text', models.CharField(blank=True, max_length=50, verbose_name='شارة (مثل: الأكثر مبيعاً)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'باقة تصاميم',
                'verbose_name_plural': '🎨 باقات تصاميم AI',
                'ordering': ['sort_order', 'designs_count'],
            },
        ),
        migrations.CreateModel(
            name='DesignPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('designs_total', models.IntegerField()),
                ('designs_used', models.IntegerField(default=0)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('paymob', 'بطاقة ائتمان (Paymob)'), ('vodafone_cash', 'فودافون كاش'), ('instapay', 'إنستاباي'), ('cash_collect', 'دفع عند الاستلام'), ('admin_grant', 'منحة من الإدارة')], default='paymob', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'في انتظار الدفع'), ('paid', 'مدفوعة — جاهزة للاستخدام'), ('exhausted', 'تم استهلاكها بالكامل'), ('refunded', 'مردودة'), ('expired', 'منتهية الصلاحية')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_purchases', to='clients.marketplacecustomer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='clients.designpackage')),
            ],
            options={
                'verbose_name': 'شراء باقة تصاميم',
                'verbose_name_plural': '🛒 مشتريات باقات التصاميم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التصميم')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('category', models.CharField(choices=[('logo', 'لوجو / Brand Mark'), ('business_card', 'كارت بزنس'), ('social_post', 'بوست سوشيال ميديا'), ('flyer', 'فلاير'), ('poster', 'بوستر / إعلان'), ('banner', 'بنر / Roll-up'), ('packaging', 'تغليف / منتج'), ('tshirt', 'تيشرت / Merch'), ('menu', 'منيو'), ('invitation', 'دعوة / كارت'), ('sticker', 'ستيكر'), ('mockup', 'Mockup منتج'), ('other', 'أخرى')], default='other', max_length=20)),
                ('size_preset', models.CharField(choices=[('1024x1024', '🟦 مربع — 1024×1024 (سوشيال ميديا)'), ('1024x1792', '📱 قصة — 1024×1792 (Story / Reel)'), ('1792x1024', '🖥️ أفقي — 1792×1024 (بنر / غلاف)'), ('2048x2048', '⚡ مربع HD — 2048×2048 (طباعة)'), ('a4', '📄 A4 — 2480×3508 (فلاير / بوستر)'), ('a3', '📑 A3 — 3508×4960 (بوستر كبير)'), ('business_card', '💳 كارت بزنس — 1050×600 (3.5×2 بوصة)'), ('tshirt_chest', '👕 تيشرت صدر — 3600×4500'), ('mug', '☕ ماج — 2700×1080'), ('custom', '⚙️ مقاس مخصص')], default='1024x1024', max_length=30, verbose_name='المقاس')),
                ('custom_width_px', models.IntegerField(blank=True, null=True, verbose_name='العرض (px)')),
                ('custom_height_px', models.IntegerField(blank=True, null=True, verbose_name='الارتفاع (px)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='وزن المنتج (اختياري — للـ packaging)')),
                ('output_format', models.CharField(choices=[('png', 'PNG'), ('jpg', 'JPEG'), ('webp', 'WebP'), ('pdf', 'PDF Print-Ready')], default='png', max_length=10)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='ai_store/logos/')),
                ('raw_input', models.TextField(blank=True)),
                ('engineered_prompt', models.TextField(blank=True)),
                ('negative_prompt', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=600)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('regenerations_used', models.IntegerField(default=0)),
                ('regenerations_allowed', models.IntegerField(default=3)),
                ('sent_to_whatsapp', models.CharField(blank=True, max_length=30)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('customer_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='clients.marketplacecustomer')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='clients.designpurchase')),
            ],
            options={
                'verbose_name': 'تصميم للعميل',
                'verbose_name_plural': '🖼️ تصاميم العملاء (AI Store)',
                'ordering': ['-created_at'],
            },
        ),
    ]
