# Generated by Django 4.2.30 on 2026-05-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_seed_design_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpurchase',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم المرسل'),
        ),
        migrations.AlterField(
            model_name='designpurchase',
            name='status',
            field=models.CharField(choices=[('pending', 'في انتظار الدفع'), ('awaiting_confirm', 'في انتظار تأكيد الدفع'), ('paid', 'مدفوعة — جاهزة للاستخدام'), ('rejected', 'مرفوضة'), ('exhausted', 'تم استهلاكها بالكامل'), ('refunded', 'مردودة'), ('expired', 'منتهية الصلاحية')], db_index=True, default='pending', max_length=20),
        ),
    ]
