# Generated by Django 4.2.30 on 2026-05-30 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_add_design_purchase_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdesign',
            name='is_free_trial',
            field=models.BooleanField(default=False, verbose_name='تصميم مجاني (تجربة)'),
        ),
        migrations.AddField(
            model_name='designpackage',
            name='designer_designs_count',
            field=models.IntegerField(default=0, help_text='نفس السعر لكن عدد أكبر للمصممين. 0 = نفس عدد العملاء', verbose_name='عدد التصاميم (مصمم)'),
        ),
        migrations.AddField(
            model_name='marketplacecustomer',
            name='free_designs_total',
            field=models.IntegerField(default=0, help_text='فرد = 2 مجاني، شركة = 4 مجاني. يتم تعيينها تلقائياً عند التسجيل', verbose_name='تصاميم مجانية (إجمالي)'),
        ),
        migrations.AddField(
            model_name='marketplacecustomer',
            name='free_designs_used',
            field=models.IntegerField(default=0, verbose_name='تصاميم مجانية مستخدمة'),
        ),
        migrations.AlterField(
            model_name='customerdesign',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='clients.designpurchase', verbose_name='الباقة (فارغ = تصميم مجاني)'),
        ),
        migrations.AlterField(
            model_name='designpackage',
            name='designs_count',
            field=models.IntegerField(verbose_name='عدد التصاميم (عميل)'),
        ),
        migrations.AlterField(
            model_name='designpackage',
            name='free_regenerations_per_design',
            field=models.IntegerField(default=2, verbose_name='إعادة توليد مجاني (2 محاولة)'),
        ),
        migrations.AlterField(
            model_name='globalb2bmarketplace',
            name='ai_quality_confidence',
            field=models.IntegerField(default=95, help_text='مؤشر ذكاء اصطناعي لجودة هذا الصنف من هذا التاجر', verbose_name='مؤشر جودة AI'),
        ),
    ]
