# Generated by Django 4.2.30 on 2026-05-30 20:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_ai_design_pricing_overhaul'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpackage',
            name='target_audience',
            field=models.CharField(choices=[('customer', 'عملاء أفراد'), ('designer', 'مصممين / شركات')], default='customer', max_length=10, verbose_name='الفئة المستهدفة'),
        ),
        migrations.AlterField(
            model_name='designpackage',
            name='slug',
            field=models.CharField(choices=[('starter', '🥉 Starter — 25 تصميم'), ('pro', '🥈 Pro — 50 تصميم'), ('business', '🥇 Business — 100 تصميم'), ('studio', '💎 Studio — 250 تصميم'), ('single', '🎯 تصميم واحد'), ('cust_2', '👤 باقة 2 تصميم'), ('cust_4', '👤 باقة 4 تصاميم'), ('cust_8', '👤 باقة 8 تصاميم'), ('des_15', '🎨 باقة 15 تصميم'), ('des_25', '🎨 باقة 25 تصميم'), ('des_50', '🎨 باقة 50 تصميم'), ('des_100', '🎨 باقة 100 تصميم')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='DesignPrintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_type', models.CharField(choices=[('tshirt', 'تيشرت'), ('business_card', 'كارت بزنس'), ('flyer', 'فلاير'), ('poster', 'بوستر'), ('banner', 'بنر / ستاند'), ('mug', 'ماج'), ('sticker', 'ستيكر'), ('packaging', 'تغليف / علبة'), ('pen', 'قلم / هدايا'), ('notebook', 'نوت بوك / أجندة'), ('menu', 'منيو'), ('invitation', 'كارت دعوة'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المنتج')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='العرض (سم)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='الطول (سم)')),
                ('paper_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الورق / الخامة')),
                ('color_mode', models.CharField(choices=[('full_color', 'ألوان كاملة'), ('bw', 'أبيض وأسود'), ('spot', 'ألوان محددة')], default='full_color', max_length=20, verbose_name='الألوان')),
                ('finishing', models.CharField(blank=True, help_text='سوفت تاتش، لامع، مطفي، UV، إلخ', max_length=100, verbose_name='التشطيب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('delivery_address', models.TextField(blank=True, verbose_name='عنوان التوصيل')),
                ('delivery_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم التواصل')),
                ('status', models.CharField(choices=[('pending', 'في انتظار المراجعة'), ('quoted', 'تم إرسال عرض سعر'), ('marketplace', 'تم نشره في السوق'), ('accepted', 'العميل قبل العرض'), ('in_production', 'قيد الطباعة'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], db_index=True, default='pending', max_length=20)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر المقترح من المنصة')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_requests', to='clients.marketplacecustomer')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_requests', to='clients.customerdesign')),
            ],
            options={
                'verbose_name': 'طلب طباعة تصميم',
                'verbose_name_plural': '🖨️ طلبات طباعة تصاميم',
                'ordering': ['-created_at'],
            },
        ),
    ]
