# Generated by Django 4.2.30 on 2026-05-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_design_packages_v2_print_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPromptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=30, verbose_name='التصنيف')),
                ('user_prompt', models.TextField(verbose_name='البرومبت الأصلي من العميل')),
                ('engineered_prompt', models.TextField(verbose_name='البرومبت المحسّن للـ AI')),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('size_used', models.CharField(blank=True, max_length=30)),
                ('customer_rating', models.IntegerField(blank=True, null=True, verbose_name='تقييم العميل (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_logs', to='clients.customerdesign')),
            ],
            options={
                'verbose_name': 'سجل برومبت',
                'verbose_name_plural': '🧠 سجلات تعلم البرومبت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', '-customer_rating'], name='clients_des_categor_148395_idx')],
            },
        ),
    ]
