# Generated by Django 4.2.30 on 2026-05-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_prompt_log_pricing_v3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='plan',
            field=models.CharField(choices=[('silver', 'باقة سيلفر — لمراكز الصيانة وتجار قطع الغيار'), ('gold', 'باقة جولد — لمراكز الصيانة وتجار قطع الغيار الشامل'), ('empire', 'باقة Empire — لتجار القطع والشركات الكبيرة'), ('print_basic', 'Print Basic — للمطابع الصغيرة واستوديوهات التصميم'), ('print_pro', 'Print Pro — للمطابع المتوسطة ومكاتب التصميم'), ('print_enterprise', 'Print Enterprise — للمطابع الكبيرة ومجموعات التصميم')], default='gold', max_length=20, verbose_name='الباقة'),
        ),
    ]
