# Generated by Django 4.2.30 on 2026-05-31 07:15

from django.db import migrations, models


def approve_existing_open_requests(apps, schema_editor):
    """Mark all existing open/reviewing/accepted/completed requests as approved."""
    ServiceRequest = apps.get_model('clients', 'ServiceRequest')
    ServiceRequest.objects.filter(
        status__in=['open', 'reviewing', 'accepted', 'completed']
    ).update(is_approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_add_printing_plan_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الإدارة'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='موافقة الإدارة'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'في انتظار موافقة الإدارة'), ('open', 'مفتوح — في انتظار العروض'), ('reviewing', 'جاري مراجعة العروض'), ('accepted', 'تم قبول عرض'), ('completed', 'مكتمل — تم التقييم'), ('expired', 'منتهي الصلاحية'), ('cancelled', 'ملغي بواسطة العميل'), ('rejected_by_admin', 'مرفوض من الإدارة')], db_index=True, default='pending_approval', max_length=20),
        ),
        # Mark existing requests as approved so they don't disappear
        migrations.RunPython(approve_existing_open_requests, migrations.RunPython.noop),
    ]
