# Generated by Django 4.2.30 on 2026-05-31 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_add_marketplace_approval_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdesign',
            name='category',
            field=models.CharField(choices=[('logo', 'لوجو / Brand Mark'), ('business_card', 'كارت بزنس'), ('letterhead', 'ورق رسمي'), ('stamp', 'ختم'), ('social_post', 'بوست سوشيال ميديا'), ('story', 'ستوري / Reels'), ('cover', 'غلاف فيسبوك / يوتيوب'), ('flyer', 'فلاير'), ('poster', 'بوستر / إعلان'), ('banner', 'بنر / Roll-up'), ('sign', 'يافطة / كلادينج'), ('menu', 'منيو'), ('invitation', 'دعوة / كارت'), ('certificate', 'شهادة'), ('brochure', 'بروشور'), ('receipt_form', 'فاتورة / نموذج'), ('tshirt', 'تيشرت / Merch'), ('pants', 'بنطلون / ملابس'), ('abaya', 'عباية / جلابية'), ('uniform', 'يونيفورم'), ('cap', 'كاب / طاقية'), ('bag', 'شنطة / حقيبة'), ('shoe', 'حذاء / جزمة'), ('packaging', 'تغليف / منتج'), ('label', 'ليبل / ملصق'), ('sticker', 'ستيكر'), ('mug_design', 'تصميم ماج'), ('mockup', 'Mockup منتج'), ('film_poster', 'بوستر فيلم'), ('book_cover', 'غلاف كتاب'), ('album_cover', 'غلاف ألبوم'), ('thumbnail', 'Thumbnail يوتيوب'), ('pattern', 'باترن / نقشة'), ('illustration', 'رسم توضيحي'), ('infographic', 'إنفوجرافيك'), ('car_wrap', 'رسم سيارة / Wrap'), ('other', 'أخرى')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerdesign',
            name='size_preset',
            field=models.CharField(choices=[('auto', '🤖 تلقائي'), ('1024x1024', '🟦 مربع 1:1'), ('1024x1536', '📱 طولي 2:3'), ('1536x1024', '🖥️ أفقي 3:2'), ('1024x1792', '📱 قصة 1024×1792'), ('1792x1024', '🖥️ عريض 1792×1024'), ('2048x2048', '⚡ مربع HD'), ('a4', '📄 A4'), ('a3', '📑 A3'), ('a5', '📃 A5'), ('business_card', '💳 كارت بزنس'), ('banner_wide', '🪧 بنر عريض'), ('rollup', '📐 Roll-up'), ('sign_square', '🏗️ يافطة مربعة'), ('sign_landscape', '🏗️ يافطة أفقية'), ('tshirt_chest', '👕 تيشرت صدر'), ('tshirt_full', '👕 تيشرت كامل'), ('pants_pattern', '👖 بنطلون'), ('abaya_pattern', '🧕 عباية / جلابية'), ('full_body', '🧍 Full Body'), ('mug', '☕ ماج'), ('bag', '👜 شنطة'), ('book_cover', '📚 غلاف كتاب'), ('youtube_thumb', '🖱️ Thumbnail'), ('film_poster', '🎬 بوستر فيلم'), ('custom', '⚙️ مقاس مخصص')], default='1024x1024', max_length=30, verbose_name='المقاس'),
        ),
        migrations.CreateModel(
            name='DesignChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'العميل'), ('assistant', 'المصمم AI'), ('system', 'النظام')], default='user', max_length=10)),
                ('content', models.TextField(verbose_name='محتوى الرسالة')),
                ('image_url', models.URLField(blank=True, max_length=600, verbose_name='صورة مرفقة')),
                ('is_refinement', models.BooleanField(default=False, verbose_name='تعديل تحسيني')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='clients.customerdesign')),
            ],
            options={
                'verbose_name': 'رسالة تصميم',
                'verbose_name_plural': '💬 رسائل التصاميم (Chat)',
                'ordering': ['created_at'],
            },
        ),
    ]
