# Generated by Django 4.2.30 on 2026-06-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_add_design_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacecustomer',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تسجيل دخول'),
        ),
        migrations.AddField(
            model_name='marketplacecustomer',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='كلمة المرور (مُشفّرة)'),
        ),
    ]
