# Generated by Django 4.2.30 on 2026-06-01 11:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_marketplacecustomer_last_login_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='monthly_ai_designs_quota',
            field=models.IntegerField(default=0, help_text='عدد التصاميم المجانية التي تحصل عليها الشركة شهرياً مع الاشتراك', verbose_name='حصة تصاميم AI شهرياً'),
        ),
        migrations.CreateModel(
            name='TenantDesignTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('designs_total', models.IntegerField(verbose_name='إجمالي التصاميم')),
                ('designs_used', models.IntegerField(default=0, verbose_name='المستهلك')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر المدفوع (ج.م)')),
                ('payment_method', models.CharField(choices=[('paymob', 'Paymob (Visa/Mastercard)'), ('vodafone_cash', 'فودافون كاش'), ('instapay', 'إنستاباي'), ('admin_grant', 'منحة إدارية')], default='paymob', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'في انتظار الدفع'), ('paid', 'مدفوعة — جاهزة للاستخدام'), ('exhausted', 'تم استهلاكها بالكامل'), ('refunded', 'مردودة'), ('expired', 'منتهية الصلاحية')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في (اختياري)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_topups', to='clients.client')),
            ],
            options={
                'verbose_name': 'شحن تصاميم للشركة',
                'verbose_name_plural': '💳 شحنات تصاميم الشركات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='clients_ten_tenant__bd308c_idx')],
            },
        ),
    ]
