# Generated by Django 4.2.30 on 2026-06-01 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0026_seed_plan_quotas_and_topups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designpackage',
            name='slug',
            field=models.CharField(choices=[('starter', '🥉 Starter — 25 تصميم'), ('pro', '🥈 Pro — 50 تصميم'), ('business', '🥇 Business — 100 تصميم'), ('studio', '💎 Studio — 250 تصميم'), ('cust_50', '🎯 باقة 50 تصميم — 25 ج.م'), ('cust_100', '🎯 باقة 100 تصميم — 35 ج.م'), ('cust_500', '🎯 باقة 500 تصميم — 150 ج.م'), ('comp_1000', '🏢 باقة الشركات 1000 تصميم — 250 ج.م'), ('comp_2500', '🏢 باقة الشركات 2500 تصميم — 500 ج.م'), ('comp_5000', '🏢 باقة الشركات 5000 تصميم — 900 ج.م'), ('des_15', '🎨 باقة 15 تصميم'), ('des_25', '🎨 باقة 25 تصميم'), ('des_50', '🎨 باقة 50 تصميم'), ('des_100', '🎨 باقة 100 تصميم')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='AIPromptLearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('customer', 'عميل سوق'), ('tenant', 'شركة / تاجر'), ('anonymous', 'زائر')], db_index=True, default='anonymous', max_length=12)),
                ('raw_input', models.TextField(verbose_name='الفكرة الخام كما كتبها المستخدم')),
                ('detected_domain', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='المجال اللي حدده الـ LLM')),
                ('dynamic_schema', models.JSONField(blank=True, default=dict, verbose_name='الـ JSON Schema الديناميكي')),
                ('selections', models.JSONField(blank=True, default=dict, verbose_name='اختيارات المستخدم')),
                ('mega_prompt', models.TextField(blank=True, verbose_name='الـ Mega Prompt النهائي')),
                ('negative_prompt', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=600)),
                ('image_size', models.CharField(blank=True, max_length=20)),
                ('llm_model', models.CharField(blank=True, max_length=80)),
                ('image_model', models.CharField(blank=True, max_length=80)),
                ('is_successful', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='هل التصميم ناجح؟ (feedback من المستخدم)')),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_learning_logs', to='clients.marketplacecustomer')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_learning_logs', to='clients.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل تعلم AI',
                'verbose_name_plural': '🌀 Data Flywheel — سجلات تعلم الذكاء',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['detected_domain', '-created_at'], name='clients_aip_detecte_18916c_idx'), models.Index(fields=['is_successful', '-created_at'], name='clients_aip_is_succ_21bd63_idx')],
            },
        ),
    ]
