# Generated by Django 4.2.30 on 2026-06-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_merge_20260601_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designpackage',
            name='slug',
            field=models.CharField(choices=[('starter', '🥉 Starter — 25 تصميم'), ('pro', '🥈 Pro — 50 تصميم'), ('business', '🥇 Business — 100 تصميم'), ('studio', '💎 Studio — 250 تصميم'), ('cust_50', '🎯 باقة 50 تصميم — 25 ج.م'), ('cust_100', '🎯 باقة 100 تصميم — 35 ج.م'), ('cust_500', '🎯 باقة 500 تصميم — 150 ج.م'), ('comp_1000', '🏢 باقة الشركات 1000 تصميم — 250 ج.م'), ('comp_2500', '🏢 باقة الشركات 2500 تصميم — 500 ج.م'), ('comp_5000', '🏢 باقة الشركات 5000 تصميم — 900 ج.م'), ('des_15', '🎨 باقة 15 تصميم'), ('des_25', '🎨 باقة 25 تصميم'), ('des_50', '🎨 باقة 50 تصميم'), ('des_100', '🎨 باقة 100 تصميم')], max_length=20, unique=True),
        ),
    ]
