# Generated by Django 4.2.30 on 2026-06-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_alter_designpackage_slug'),
        ('clients', '0028_phase0a_backfill_tenant_subscriptions'),
    ]

    operations = [
    ]
