# Generated by Django 4.2.30 on 2026-06-02 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0030_seed_feature_catalog_and_plan_entitlements'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscription',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تثبيت الـ snapshot'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='locked_entitlements',
            field=models.JSONField(blank=True, default=dict, help_text='نسخة من Plan.entitlements وقت الاشتراك/التجديد', verbose_name='الصلاحيات المثبتة (snapshot)'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='locked_monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='نسخة من Plan.monthly_price وقت الاشتراك/التجديد', max_digits=10, null=True, verbose_name='السعر المثبت (snapshot)'),
        ),
        migrations.CreateModel(
            name='PlanRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الشهري')),
                ('entitlements', models.JSONField(blank=True, default=dict, verbose_name='الصلاحيات')),
                ('change_reason', models.CharField(blank=True, max_length=250, verbose_name='سبب التغيير')),
                ('effective_from', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفعل')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_revisions_authored', to=settings.AUTH_USER_MODEL, verbose_name='غيّر بواسطة')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='clients.plan', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'revision باقة',
                'verbose_name_plural': '📜 سجل تعديلات الباقات',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='locked_plan_revision',
            field=models.ForeignKey(blank=True, help_text='للـ audit — أي إصدار من الـ plan كان وقت الـ snapshot', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locked_subscriptions', to='clients.planrevision', verbose_name='revision المرجعية'),
        ),
        migrations.AddIndex(
            model_name='planrevision',
            index=models.Index(fields=['plan', '-effective_from'], name='clients_pla_plan_id_7edb4e_idx'),
        ),
    ]
