# Generated by Django 4.2.30 on 2026-06-02 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_merge_20260602_0427'),
        ('clients', '0030_seed_feature_catalog_and_plan_entitlements'),
    ]

    operations = [
    ]
