# Generated by Django 4.2.30 on 2026-06-02 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_merge_20260602_0442'),
        ('clients', '0032_backfill_revisions_and_snapshots'),
    ]

    operations = [
    ]
