# Generated by Django 4.2.30 on 2026-06-02 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0032_backfill_revisions_and_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.SlugField(blank=True, help_text='auto-generated في save() بصيغة INV-YYYY-NNNNNN', max_length=30, unique=True, verbose_name='رقم الفاتورة')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('billing_cycle_months', models.IntegerField(verbose_name='عدد الشهور')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي قبل الخصم')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='نسبة الخصم (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الخصم')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي المستحق')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('entitlements_snapshot', models.JSONField(blank=True, default=dict, help_text='immutable — للـ audit والـ legal لو حصل dispute', verbose_name='نسخة المزايا وقت الفوترة')),
                ('status', models.CharField(choices=[('issued', 'مصدرة (لم تُدفع بعد)'), ('paid', 'مدفوعة'), ('failed', 'فشلت المعالجة'), ('refunded', 'مردودة'), ('void', 'ملغاة')], db_index=True, default='issued', max_length=12)),
                ('payment_provider', models.CharField(blank=True, max_length=20, verbose_name='بوابة الدفع')),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='مرجع الدفع')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أصدرها')),
                ('plan_revision', models.ForeignKey(help_text='الإصدار اللي اتفوتر عليه — مهم للـ audit والـ legal', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.planrevision', verbose_name='revision الباقة')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.tenantsubscription', verbose_name='الاشتراك')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_invoices', to='clients.client', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'فاتورة منصة',
                'verbose_name_plural': '💸 فواتير المنصة (SaaS)',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['tenant', '-issued_at'], name='clients_pla_tenant__164cfa_idx'), models.Index(fields=['status', '-issued_at'], name='clients_pla_status_831d55_idx'), models.Index(fields=['payment_provider', 'payment_reference'], name='clients_pla_payment_b8e969_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='platforminvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_reference__gt', '')), fields=('payment_provider', 'payment_reference'), name='unique_provider_payment_ref'),
        ),
    ]
