# Generated by Django 4.2.30 on 2026-06-02 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_merge_20260602_0453'),
        ('clients', '0033_platform_invoice'),
    ]

    operations = [
    ]
