# Generated by Django 4.2.30 on 2026-06-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_backfill_missing_tenant_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='designprintrequest',
            name='print_spec_pdf',
            field=models.FileField(blank=True, help_text='PDF بكل تفاصيل الطباعة (نص + لون + خامة + مقاسات) — يتولّد تلقائياً', null=True, upload_to='marketplace/print_specs/', verbose_name='ملف PDF بمواصفات الطباعة'),
        ),
    ]
