# Generated by Django 4.2.30 on 2026-06-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_add_print_spec_pdf_to_designprintrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscription',
            name='diag_api_last_refill_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='diag_api_quota_remaining',
            field=models.IntegerField(default=0, help_text='بـ تتدفع 1 لكل external API call يـ miss الـ cache. الـ refill شهرياً أو يدوياً.', verbose_name='حصة فحوصات الـ API المتبقية'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='diag_api_scans_used_total',
            field=models.IntegerField(default=0, verbose_name='إجمالي فحوصات API المستهلكة (lifetime)'),
        ),
    ]
