# Generated by Django 4.2.30 on 2026-06-04 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0037_tenantsubscription_diag_api_last_refill_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticsAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='اسم الحزمة')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الشهري (ج.م)')),
                ('monthly_api_quota', models.IntegerField(default=200, help_text='بـ يـ refill diag_api_quota_remaining في 1st كل شهر', verbose_name='حصة فحوصات API الخارجية شهرياً')),
                ('entitlements', models.JSONField(blank=True, default=dict, help_text='dict من feature_code → {enabled: bool, monthly_limit?: int}', verbose_name='الصلاحيات (entitlements)')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='مميزات الحزمة (للعرض على الـ pricing page)')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'حزمة Smart Diagnostics',
                'verbose_name_plural': '🔧 حزم Smart Diagnostics (Add-ons)',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='diagnostics_addon',
            field=models.ForeignKey(blank=True, help_text='اختياري — يفعّل ميزات التشخيص الذكي فوق الباقة الأساسية', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.diagnosticsaddon', verbose_name='🔧 حزمة Smart Diagnostics'),
        ),
    ]
