# Generated by Django 4.2.30 on 2026-06-04 17:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0040_customer_brand_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='رمز المحادثة')),
                ('brand_profile_snapshot', models.JSONField(blank=True, default=dict, verbose_name='لقطة من ملف البراند وقت بدء المحادثة')),
                ('accumulated_context', models.JSONField(blank=True, default=dict, verbose_name='السياق المتراكم عبر التيرنات')),
                ('stage', models.CharField(choices=[('planning', 'تخطيط — لسه بنتكلم'), ('generated', 'اتولّد أول تصميم'), ('refining', 'قيد التعديل'), ('finalized', 'تم الاعتماد'), ('abandoned', 'متروك')], db_index=True, default='planning', max_length=12, verbose_name='المرحلة')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='مقفول حتى (advisory lock)')),
                ('turn_count', models.PositiveSmallIntegerField(default=0, verbose_name='عدد التيرنات')),
                ('image_count', models.PositiveSmallIntegerField(default=0, verbose_name='عدد الصور المولّدة')),
                ('total_cost_credits', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='التكلفة الإجمالية (credits)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('abandoned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '💬 محادثة تصميم',
                'verbose_name_plural': '💬 محادثات التصاميم',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_index', models.PositiveSmallIntegerField(help_text='بداية من 1 — يـ increment على كل user message', verbose_name='ترتيب التيرن')),
                ('role', models.CharField(choices=[('user', 'العميل'), ('assistant', 'المصمم AI'), ('system', 'النظام')], max_length=10)),
                ('content', models.TextField(verbose_name='محتوى الرسالة')),
                ('intent', models.CharField(choices=[('chat', 'دردشة (بدون توليد)'), ('generate', 'توليد صورة جديدة'), ('refine', 'تعديل الصورة الحالية'), ('undo', 'رجوع للحالة السابقة'), ('finalize', 'اعتماد التصميم'), ('unknown', 'غير محدد')], db_index=True, default='unknown', max_length=12, verbose_name='النية المصنّفة')),
                ('intent_confidence', models.FloatField(default=0.0, verbose_name='ثقة المصنِّف (0-1)')),
                ('token_cost_credits', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='تكلفة الـ tokens')),
                ('image_cost_credits', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='تكلفة الصورة')),
                ('engine_used', models.CharField(blank=True, help_text='flux | ideogram | kontext | llm_only', max_length=20, verbose_name='المحرك المستخدم')),
                ('context_patch', models.JSONField(blank=True, default=dict, verbose_name='التعديل على السياق هذا التيرن')),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': '💬 تيرن محادثة تصميم',
                'verbose_name_plural': '💬 تيرنات محادثات التصاميم',
                'ordering': ['conversation', 'turn_index', 'created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='aipromptlearninglog',
            new_name='clients_aip_present_2c1bed_idx',
            old_name='clients_aip_pres_subtype_idx',
        ),
        migrations.RenameIndex(
            model_name='aipromptlearninglog',
            new_name='clients_aip_quality_e64e51_idx',
            old_name='clients_aip_qverdict_idx',
        ),
        migrations.AlterField(
            model_name='customerbrandprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='designconversationturn',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='clients.designconversation', verbose_name='المحادثة'),
        ),
        migrations.AddField(
            model_name='designconversationturn',
            name='design_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_snapshots', to='clients.customerdesign', verbose_name='صورة التيرن'),
        ),
        migrations.AddField(
            model_name='designconversation',
            name='current_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_conversations', to='clients.customerdesign', verbose_name='التصميم الحالي'),
        ),
        migrations.AddField(
            model_name='designconversation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_conversations', to='clients.marketplacecustomer', verbose_name='العميل'),
        ),
        migrations.AddIndex(
            model_name='designconversationturn',
            index=models.Index(fields=['conversation', 'turn_index'], name='clients_des_convers_ca4684_idx'),
        ),
        migrations.AddIndex(
            model_name='designconversationturn',
            index=models.Index(fields=['intent', '-created_at'], name='clients_des_intent_cfdbde_idx'),
        ),
        migrations.AddConstraint(
            model_name='designconversationturn',
            constraint=models.UniqueConstraint(fields=('conversation', 'turn_index', 'role'), name='uniq_conv_turn_role'),
        ),
        migrations.AddIndex(
            model_name='designconversation',
            index=models.Index(fields=['customer', 'stage'], name='clients_des_custome_f358d7_idx'),
        ),
        migrations.AddIndex(
            model_name='designconversation',
            index=models.Index(fields=['stage', '-updated_at'], name='clients_des_stage_058ee1_idx'),
        ),
    ]
