# Generated by Django 4.2.30 on 2026-06-06 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0041_design_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBDDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, help_text="Human label e.g. 'Branch-Cairo Bay 2'", max_length=120)),
                ('branch_id', models.PositiveIntegerField(blank=True, help_text='Branch PK within tenant schema', null=True)),
                ('secret_ciphertext', models.BinaryField()),
                ('secret_last4', models.CharField(help_text='Ops-UI hint only', max_length=4)),
                ('rotation_generation', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('replay_window_seconds', models.PositiveSmallIntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen_generation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obd_devices', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='OBDDeviceNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=64)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonces', to='clients.obddevice')),
            ],
            options={
                'indexes': [models.Index(fields=['seen_at'], name='clients_obd_seen_at_cfe9b8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='obddevicenonce',
            constraint=models.UniqueConstraint(fields=('device', 'nonce'), name='uniq_obd_device_nonce'),
        ),
        migrations.AddIndex(
            model_name='obddevice',
            index=models.Index(fields=['tenant', 'status'], name='clients_obd_tenant__a60736_idx'),
        ),
    ]
