# Generated by Django 4.2.30 on 2026-06-08 16:31

import clients.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0043_customer_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='الماركة')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='parts/makes/')),
                ('sort_order', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('listings_count', models.IntegerField(default=0, help_text='Cached count of active listings')),
            ],
            options={
                'verbose_name': 'ماركة سيارة',
                'verbose_name_plural': '🏷️ ماركات السيارات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='اسم القطعة')),
                ('description', models.TextField(help_text='اوصف القطعة بالتفصيل: الحالة، أي عيوب، رقم القطعة الأصلي، إلخ', verbose_name='الوصف')),
                ('car_model', models.CharField(blank=True, help_text='مثال: 320i, X5, Cooper S', max_length=100, verbose_name='الموديل')),
                ('car_year_from', models.IntegerField(blank=True, null=True, verbose_name='من سنة')),
                ('car_year_to', models.IntegerField(blank=True, null=True, verbose_name='إلى سنة')),
                ('part_number', models.CharField(blank=True, max_length=120, verbose_name='رقم القطعة الأصلي (OEM)')),
                ('condition', models.CharField(choices=[('new', 'جديد بالضمانة'), ('used_excellent', 'مستعمل — ممتاز'), ('used_good', 'مستعمل — جيد'), ('used_fair', 'مستعمل — مقبول'), ('refurbished', 'مجدد')], default='used_good', max_length=20)),
                ('price_egp', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر (ج.م)')),
                ('warranty_days', models.IntegerField(default=3, help_text='بعد التسليم — كلما طالت الفترة زادت ثقة المشتري (الحد الأقصى 90 يوم)', validators=[clients.models._validate_warranty_days], verbose_name='فترة الضمان (يوم)')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('reserved', 'محجوز'), ('sold', 'تم البيع'), ('removed', 'محذوف')], db_index=True, default='draft', max_length=20)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='clients.partcarmake', verbose_name='ماركة السيارة')),
                ('seller_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_listings', to='clients.marketplacecustomer', verbose_name='البائع (عميل سوق)')),
                ('seller_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_listings', to='clients.client', verbose_name='البائع (شركة)')),
            ],
            options={
                'verbose_name': 'قطعة غيار معروضة',
                'verbose_name_plural': '🛒 سوق قطع الغيار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parts/listings/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='clients.partlisting')),
            ],
            options={
                'ordering': ['-is_primary', 'sort_order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('seller_payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('warranty_days', models.IntegerField()),
                ('status', models.CharField(choices=[('pending_payment', 'بانتظار الدفع'), ('paid_held', 'مدفوع — في الـ Escrow'), ('shipped', 'في الشحن'), ('delivered', 'تم التسليم — في فترة الضمان'), ('released', 'تم الإفراج — أُرسلت للبائع'), ('refund_requested', 'طلب إرجاع'), ('refunded', 'تم الإرجاع للمشتري'), ('disputed', 'نزاع — قيد المراجعة'), ('cancelled', 'ملغي')], db_index=True, default='pending_payment', max_length=20)),
                ('shipping_name', models.CharField(blank=True, max_length=120)),
                ('shipping_phone', models.CharField(blank=True, max_length=30)),
                ('shipping_address', models.TextField(blank=True)),
                ('shipping_city', models.CharField(blank=True, max_length=80)),
                ('paymob_order_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('paymob_txn_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('warranty_ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('buyer_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_orders', to='clients.marketplacecustomer')),
                ('buyer_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_orders', to='clients.client')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.partlisting')),
            ],
            options={
                'verbose_name': 'طلب شراء قطعة',
                'verbose_name_plural': '📦 طلبات شراء قطع الغيار',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'warranty_ends_at'], name='clients_par_status_bcc892_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='partorder',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('buyer_customer__isnull', False), ('buyer_tenant__isnull', True)), models.Q(('buyer_customer__isnull', True), ('buyer_tenant__isnull', False)), _connector='OR'), name='partorder_one_buyer'),
        ),
        migrations.AddIndex(
            model_name='partlisting',
            index=models.Index(fields=['status', 'car_make'], name='clients_par_status_abd1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='partlisting',
            index=models.Index(fields=['status', '-created_at'], name='clients_par_status_3d82f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='partlisting',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('seller_customer__isnull', False), ('seller_tenant__isnull', True)), models.Q(('seller_customer__isnull', True), ('seller_tenant__isnull', False)), _connector='OR'), name='partlisting_one_seller'),
        ),
    ]
