# Generated by Django 4.2.30 on 2026-06-10 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0045_seed_car_makes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('alive_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(blank=True, db_index=True, default='', max_length=63)),
                ('tenant_name', models.CharField(blank=True, default='', max_length=100)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(db_index=True)),
                ('exception_class', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('traceback', models.TextField(blank=True, default='')),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('level', models.CharField(choices=[('warning', 'تحذير'), ('error', 'خطأ'), ('critical', 'حرج')], default='error', max_length=10)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل خطأ نظام',
                'verbose_name_plural': 'سجلات أخطاء النظام',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'is_resolved'], name='clients_sys_created_09df45_idx'), models.Index(fields=['tenant_schema', '-created_at'], name='clients_sys_tenant__e744db_idx')],
            },
        ),
    ]
