# Generated by Django 4.2.30 on 2026-06-10 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0046_alter_client_managers_client_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('god', 'المالك الأعلى'), ('tech_admin', 'مدير تقني'), ('support', 'موظف دعم'), ('sales', 'مبيعات'), ('finance', 'محاسبة ومالية')], max_length=20, verbose_name='الدور')),
                ('can_force_delete', models.BooleanField(default=False, verbose_name='صلاحية الحذف النهائي؟')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_role', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'دور موظف',
                'verbose_name_plural': 'أدوار موظفي الإدارة',
            },
        ),
    ]
