# Generated by Django 4.2.30 on 2026-06-10 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0047_alter_client_managers_staffrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(max_length=120, verbose_name='اسم المرسل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='الهاتف')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('in_progress', 'جاري الحل'), ('waiting', 'بانتظار رد العميل'), ('closed', 'مغلقة')], db_index=True, default='open', max_length=15)),
                ('priority', models.CharField(choices=[('low', 'عادية'), ('medium', 'متوسطة'), ('high', 'عاجلة'), ('urgent', 'طارئة')], default='medium', max_length=10)),
                ('source', models.CharField(choices=[('form', 'فورم اتصل بنا'), ('chat_offline', 'شات خارج أوقات العمل'), ('email', 'بريد إلكتروني'), ('phone', 'مكالمة هاتفية')], default='form', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='ملاحظات داخلية')),
                ('email_delivered', models.BooleanField(default=False)),
                ('email_error', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='clients.client', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'تذكرة دعم',
                'verbose_name_plural': 'تذاكر الدعم',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='clients_sup_status_354813_idx')],
            },
        ),
    ]
