# Generated by Django 4.2.30 on 2026-06-10 13:47

import clients.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0051_grandfather_active_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_obd_access',
            field=models.BooleanField(default=False, verbose_name='الوصول لغرفة التشخيص (OBD)'),
        ),
        migrations.AddField(
            model_name='client',
            name='obd_access_expiry',
            field=models.DateTimeField(blank=True, help_text='اتركها فارغة للوصول مدى الحياة.', null=True, verbose_name='انتهاء صلاحية وصول OBD'),
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('national_id', 'بطاقة رقم قومي'), ('passport', 'جواز سفر')], default='national_id', max_length=20)),
                ('id_number_last4', models.CharField(blank=True, default='', help_text='نخزّن آخر 4 أرقام فقط — التطابق الكامل يتم وقت المراجعة', max_length=4)),
                ('id_document_front', models.ImageField(blank=True, null=True, upload_to=clients.models._verification_upload_path)),
                ('id_document_back', models.ImageField(blank=True, null=True, upload_to=clients.models._verification_upload_path)),
                ('id_status', models.CharField(choices=[('not_submitted', 'لم يُقدَّم'), ('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='not_submitted', max_length=15)),
                ('id_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('id_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('id_rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('selfie_image', models.ImageField(blank=True, null=True, upload_to=clients.models._verification_upload_path)),
                ('selfie_status', models.CharField(choices=[('not_submitted', 'لم يُقدَّم'), ('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='not_submitted', max_length=15)),
                ('workshop_license_number_last4', models.CharField(blank=True, default='', max_length=8)),
                ('workshop_license_image', models.ImageField(blank=True, null=True, upload_to=clients.models._verification_upload_path)),
                ('workshop_license_status', models.CharField(choices=[('not_submitted', 'لم يُقدَّم'), ('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='not_submitted', max_length=15)),
                ('business_registration_image', models.ImageField(blank=True, null=True, upload_to=clients.models._verification_upload_path)),
                ('business_registration_status', models.CharField(choices=[('not_submitted', 'لم يُقدَّم'), ('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='not_submitted', max_length=15)),
                ('tax_card_image', models.ImageField(blank=True, null=True, upload_to=clients.models._verification_upload_path)),
                ('tax_card_status', models.CharField(choices=[('not_submitted', 'لم يُقدَّم'), ('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='not_submitted', max_length=15)),
                ('trust_score', models.IntegerField(db_index=True, default=0, help_text='0–100. يُحسب تلقائياً من حالة المستندات.')),
                ('trust_tier', models.CharField(choices=[('new', 'جديد'), ('basic', 'أساسي'), ('email', 'موثّق بالبريد'), ('id', 'هوية موثّقة'), ('business', 'عمل موثّق')], db_index=True, default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='clients.marketplacecustomer')),
                ('id_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'توثيق هوية مستخدم',
                'verbose_name_plural': '🛡️ توثيقات الهوية (KYC)',
            },
        ),
    ]
