# Generated by Django 4.2.30 on 2026-06-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0052_add_obd_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partlisting',
            name='moderation_status',
            field=models.CharField(choices=[('pending_approval', 'بانتظار موافقة الإدارة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('suspended', 'معلق بواسطة الإدارة')], db_index=True, default='pending_approval', max_length=20, verbose_name='حالة المراجعة'),
        ),
    ]
