# Generated by Django 4.2.30 on 2026-06-10 14:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0053_alter_partlisting_moderation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('held', 'محجوز'), ('released_to_seller', 'تم التحويل للبائع'), ('refunded_to_buyer', 'تم الرد للمشتري'), ('split', 'مقسوم — جزئي')], db_index=True, default='held', max_length=25)),
                ('held_amount', models.DecimalField(decimal_places=2, help_text='إجمالي المبلغ المحجوز عند الدفع.', max_digits=12)),
                ('seller_payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('buyer_refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('platform_commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('held_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'حجز ضمان (Escrow Hold)',
                'verbose_name_plural': '💰 حجوزات الضمان',
                'ordering': ['-held_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformLiabilityDisclaimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, help_text='e.g. v1.0, v1.1, v2.0', max_length=20, unique=True)),
                ('title_ar', models.CharField(default='إخلاء مسؤولية المنصة', max_length=200)),
                ('body_ar', models.TextField(help_text='النص القانوني الكامل بالعربية.')),
                ('body_en', models.TextField(blank=True, default='', help_text='Optional English mirror for international buyers.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='هل هذه النسخة المعروضة حالياً للمشترين الجدد؟')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إخلاء مسؤولية',
                'verbose_name_plural': '📜 وثائق إخلاء المسؤولية',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddField(
            model_name='partorder',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('buyer_remorse', 'تراجع المشتري'), ('wrong_size_or_fit', 'مقاس / تركيب خطأ من المشتري'), ('defective', 'القطعة معيبة'), ('incorrect', 'القطعة مختلفة عن المعروض'), ('not_as_described', 'غير مطابق للوصف / الصور'), ('never_arrived', 'لم تصل')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='partorder',
            name='return_shipping_payer',
            field=models.CharField(blank=True, choices=[('buyer', 'المشتري'), ('seller', 'البائع')], default='', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='partorder',
            constraint=models.CheckConstraint(check=models.Q(('return_shipping_payer__in', ['', 'buyer', 'seller'])), name='partorder_return_payer_never_platform'),
        ),
        migrations.AddField(
            model_name='escrowhold',
            name='accepted_disclaimer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holds', to='clients.platformliabilitydisclaimer'),
        ),
        migrations.AddField(
            model_name='escrowhold',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_hold', to='clients.partorder', verbose_name='الطلب'),
        ),
        migrations.AddField(
            model_name='escrowhold',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='escrowhold',
            constraint=models.CheckConstraint(check=models.Q(('held_amount__gte', 0), ('seller_payout_amount__gte', 0), ('buyer_refund_amount__gte', 0), ('platform_commission_amount__gte', 0)), name='escrowhold_amounts_nonnegative'),
        ),
    ]
