# Generated by Django 4.2.30 on 2026-06-10 14:30

import clients.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0055_seed_disclaimer_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='partlisting',
            name='engine_code',
            field=models.CharField(blank=True, db_index=True, help_text='مثال: N13, N20, M54, K20A — حساس جداً لمطابقة قطع غيار محرك.', max_length=30, verbose_name='كود الموتور'),
        ),
        migrations.AlterField(
            model_name='partlisting',
            name='car_model',
            field=models.CharField(blank=True, db_index=True, help_text='مثال: 320i, X5, Cooper S, F30', max_length=100, verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='partlisting',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='رقم القطعة الأصلي (OEM)'),
        ),
        migrations.CreateModel(
            name='PartWantedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, default='', max_length=255)),
                ('request_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('car_model', models.CharField(db_index=True, help_text='مثال: F30, X5, Civic — مطلوب.', max_length=100, verbose_name='الموديل')),
                ('car_year', models.IntegerField(db_index=True, help_text='سنة واحدة محددة (مطلوبة).', verbose_name='سنة الصنع')),
                ('engine_code', models.CharField(blank=True, db_index=True, help_text='N13, N20, etc. اتركه فارغاً لو القطعة هيكلية أو مش متعلقة بالمحرك.', max_length=30, verbose_name='كود الموتور')),
                ('part_name', models.CharField(max_length=200, verbose_name='اسم القطعة')),
                ('part_number_oem', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='رقم OEM (اختياري)')),
                ('description', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('max_budget_egp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الميزانية القصوى (ج.م) — اختياري')),
                ('status', models.CharField(choices=[('open', 'مفتوح — بانتظار عروض'), ('matched', 'تم قبول عرض'), ('fulfilled', 'تم الشراء'), ('cancelled', 'ملغي بواسطة المشتري'), ('expired', 'منتهي الصلاحية')], db_index=True, default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='الطلب يختفي تلقائياً بعد 14 يوم.')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_wanted_requests', to='clients.marketplacecustomer')),
                ('buyer_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_wanted_requests', to='clients.client')),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wanted_requests', to='clients.partcarmake', verbose_name='الماركة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب قطعة (Wanted)',
                'verbose_name_plural': '🆘 طلبات القطع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartWantedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_egp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition', models.CharField(choices=[('new', 'جديد بالضمانة'), ('used_excellent', 'مستعمل — ممتاز'), ('used_good', 'مستعمل — جيد'), ('used_fair', 'مستعمل — مقبول'), ('refurbished', 'مجدد')], default='used_good', max_length=20)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('warranty_days', models.IntegerField(default=3, validators=[clients.models._validate_warranty_days])),
                ('status', models.CharField(choices=[('pending', 'مرسل — بانتظار رد المشتري'), ('accepted', 'قبله المشتري'), ('rejected', 'رفضه المشتري'), ('withdrawn', 'سحبه البائع')], db_index=True, default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('linked_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wanted_offers', to='clients.partlisting')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='clients.partwantedrequest')),
                ('seller_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wanted_offers_made', to='clients.marketplacecustomer')),
                ('seller_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wanted_offers_made', to='clients.client')),
            ],
            options={
                'verbose_name': 'عرض على طلب قطعة',
                'verbose_name_plural': 'عروض على طلبات القطع',
                'ordering': ['price_egp', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='partwantedrequest',
            index=models.Index(fields=['status', 'car_make', 'car_model', 'car_year'], name='clients_par_status_3287ad_idx'),
        ),
        migrations.AddIndex(
            model_name='partwantedrequest',
            index=models.Index(fields=['status', 'engine_code'], name='clients_par_status_7a1d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='partwantedrequest',
            index=models.Index(fields=['status', 'expires_at'], name='clients_par_status_5fc7c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='partwantedrequest',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('buyer_customer__isnull', False), ('buyer_tenant__isnull', True)), models.Q(('buyer_customer__isnull', True), ('buyer_tenant__isnull', False)), _connector='OR'), name='partwanted_one_buyer'),
        ),
        migrations.AddConstraint(
            model_name='partwantedoffer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('seller_customer__isnull', False), ('seller_tenant__isnull', True)), models.Q(('seller_customer__isnull', True), ('seller_tenant__isnull', False)), _connector='OR'), name='partwantedoffer_one_seller'),
        ),
        migrations.AddConstraint(
            model_name='partwantedoffer',
            constraint=models.UniqueConstraint(fields=('request', 'seller_customer', 'seller_tenant'), name='partwantedoffer_one_per_seller_per_request'),
        ),
    ]
