# Generated by Django 4.2.30 on 2026-06-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0056_partlisting_engine_code_alter_partlisting_car_model_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='partwantedoffer',
            name='partwantedoffer_one_per_seller_per_request',
        ),
        migrations.AddConstraint(
            model_name='partwantedoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('seller_customer__isnull', False)), fields=('request', 'seller_customer'), name='partwantedoffer_one_per_customer_seller'),
        ),
        migrations.AddConstraint(
            model_name='partwantedoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('seller_tenant__isnull', False)), fields=('request', 'seller_tenant'), name='partwantedoffer_one_per_tenant_seller'),
        ),
    ]
