# Generated by Django 4.2.30 on 2026-06-10 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0057_remove_partwantedoffer_partwantedoffer_one_per_seller_per_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, default='', max_length=255)),
                ('ticket_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('opened_by_role', models.CharField(choices=[('buyer', 'المشتري'), ('seller', 'البائع')], max_length=10)),
                ('category', models.CharField(choices=[('item_not_received', 'لم تصل القطعة'), ('item_not_as_described', 'غير مطابقة للوصف'), ('damaged_on_arrival', 'وصلت تالفة'), ('wrong_item', 'قطعة مختلفة'), ('counterfeit', 'غير أصلية / تقليد'), ('buyer_misuse', 'سوء استخدام من المشتري'), ('payment_issue', 'مشكلة في الدفع'), ('other', 'أخرى')], max_length=30)),
                ('description', models.TextField(verbose_name='التفاصيل')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('under_review', 'قيد المراجعة'), ('resolved_refund', 'محلولة — رد للمشتري'), ('resolved_release', 'محلولة — تحرير للبائع'), ('resolved_split', 'محلولة — تسوية جزئية'), ('cancelled', 'ملغاة من مقدّمها')], db_index=True, default='open', max_length=20)),
                ('order_status_at_open', models.CharField(blank=True, default='', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opened_by_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes_opened', to='clients.marketplacecustomer')),
                ('opened_by_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes_opened', to='clients.client')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='clients.partorder')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تذكرة نزاع',
                'verbose_name_plural': '⚖️ تذاكر النزاعات',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disputes/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_by_role', models.CharField(blank=True, choices=[('buyer', 'المشتري'), ('seller', 'البائع')], default='', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='clients.disputeticket')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='disputeticket',
            index=models.Index(fields=['status', '-opened_at'], name='clients_dis_status_9bcaf1_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeticket',
            index=models.Index(fields=['order', 'status'], name='clients_dis_order_i_63bda3_idx'),
        ),
        migrations.AddConstraint(
            model_name='disputeticket',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('opened_by_customer__isnull', False), ('opened_by_tenant__isnull', True)), models.Q(('opened_by_customer__isnull', True), ('opened_by_tenant__isnull', False)), _connector='OR'), name='dispute_one_opener'),
        ),
    ]
