# Generated by Django 4.2.30 on 2026-06-10 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0058_disputeticket_disputeevidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDiagnosticsSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('trial', 'تجربة مجانية'), ('basic', 'Basic — 99 ج/شهر'), ('pro', 'Pro — 199 ج/شهر'), ('empire', 'Empire — 399 ج/شهر'), ('expired', 'منتهية')], db_index=True, default='trial', max_length=12)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('scans_used', models.IntegerField(default=0)),
                ('lifetime_scans', models.IntegerField(default=0)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('last_payment_egp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_payment_ref', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics_subscription', to='clients.marketplacecustomer')),
            ],
            options={
                'verbose_name': 'اشتراك تشخيص عميل',
                'verbose_name_plural': '💎 اشتراكات تشخيص العملاء',
            },
        ),
    ]
