# Generated by Django 4.2.30 on 2026-06-11 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0059_customerdiagnosticssubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('purchase_type', models.CharField(choices=[('subscription', 'اشتراك SaaS'), ('parts', 'قطع غيار'), ('design', 'باقة تصاميم'), ('diagnostics', 'ترقية تشخيص'), ('addon', 'إضافة (موظف/فرع/خزينة)')], db_index=True, max_length=20)),
                ('purchase_id', models.PositiveIntegerField(db_index=True, help_text='PK of the related DesignPurchase / PartOrder / PlatformInvoice / etc.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('vodafone_cash', 'فودافون كاش'), ('instapay', 'إنستاباي')], default='vodafone_cash', max_length=20)),
                ('sender_phone', models.CharField(max_length=20, verbose_name='رقم المرسل')),
                ('txn_reference', models.CharField(max_length=200, verbose_name='رقم العملية / Reference')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='manual_payments/%Y/%m/', verbose_name='سكرين شوت التحويل')),
                ('contact_phone', models.CharField(blank=True, help_text='Phone to call back for clarification.', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات العميل')),
                ('status', models.CharField(choices=[('pending', 'في انتظار المراجعة'), ('confirmed', 'تم التأكيد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات الأدمن')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_receipts', to='clients.marketplacecustomer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_receipts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_receipts', to='clients.client')),
            ],
            options={
                'verbose_name': 'إيصال دفع يدوي',
                'verbose_name_plural': '💵 إيصالات الدفع اليدوي (فودافون/إنستاباي)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='clients_man_status_60c126_idx'), models.Index(fields=['purchase_type', 'purchase_id'], name='clients_man_purchas_267c73_idx')],
            },
        ),
    ]
