# Generated by Django 4.2.30 on 2026-06-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0061_deactivate_legacy_design_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdesign',
            name='image_persisted_at',
            field=models.DateTimeField(blank=True, help_text='None = صورة قديمة قبل الـ persistence pipeline', null=True, verbose_name='تاريخ الحفظ المحلي'),
        ),
        migrations.AddField(
            model_name='customerdesign',
            name='image_preview_url',
            field=models.URLField(blank=True, max_length=600, verbose_name='معاينة (512px WebP)'),
        ),
        migrations.AddField(
            model_name='customerdesign',
            name='image_size_bytes',
            field=models.IntegerField(blank=True, null=True, verbose_name='حجم الصورة الأصلية (bytes)'),
        ),
        migrations.AddField(
            model_name='customerdesign',
            name='image_thumb_url',
            field=models.URLField(blank=True, max_length=600, verbose_name='صورة مصغّرة (200px WebP)'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='source',
            field=models.CharField(choices=[('form', 'فورم اتصل بنا'), ('chat_offline', 'شات خارج أوقات العمل'), ('ai_chatbot', 'المساعد الذكي'), ('email', 'بريد إلكتروني'), ('phone', 'مكالمة هاتفية')], default='form', max_length=20),
        ),
    ]
