# Generated by Django 4.2.30 on 2026-06-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0062_customerdesign_image_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticsTopUpPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='اسم الحزمة')),
                ('price_egp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر (ج.م)')),
                ('uses_granted', models.IntegerField(help_text='استخدام = فحص واحد أو سؤال بوت واحد', verbose_name='عدد الاستخدامات')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'حزمة شحن تشخيص',
                'verbose_name_plural': '🔍 حزم شحن التشخيص',
                'ordering': ['sort_order', 'price_egp'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_diagnostics_bot_quota',
            field=models.IntegerField(default=0, help_text='عدد أسئلة بوت التشخيص الذكي شهرياً', verbose_name='حصة أسئلة بوت التشخيص شهرياً'),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_diagnostics_scans_quota',
            field=models.IntegerField(default=0, help_text='عدد الفحوصات الناجحة في صفحة التشخيص شهرياً', verbose_name='حصة فحوصات التشخيص شهرياً'),
        ),
        migrations.AlterField(
            model_name='designpackage',
            name='slug',
            field=models.CharField(choices=[('starter', '🥉 Starter — 25 تصميم'), ('pro', '🥈 Pro — 50 تصميم'), ('business', '🥇 Business — 100 تصميم'), ('studio', '💎 Studio — 250 تصميم'), ('cust_50', '🎯 باقة 50 تصميم — 25 ج.م'), ('cust_100', '🎯 باقة 100 تصميم — 35 ج.م'), ('cust_500', '🎯 باقة 500 تصميم — 150 ج.م'), ('comp_1000', '🏢 باقة الشركات 1000 تصميم — 250 ج.م'), ('comp_2500', '🏢 باقة الشركات 2500 تصميم — 500 ج.م'), ('comp_5000', '🏢 باقة الشركات 5000 تصميم — 900 ج.م'), ('des_15', '🎨 باقة 15 تصميم'), ('des_25', '🎨 باقة 25 تصميم'), ('des_50', '🎨 باقة 50 تصميم'), ('des_100', '🎨 باقة 100 تصميم'), ('c10', '🎯 باقة 10 تصاميم — عميل'), ('c20', '🎯 باقة 20 تصميم — عميل'), ('c50', '🎯 باقة 50 تصميم — عميل'), ('d20', '🏢 باقة 20 تصميم — مصمم/شركة'), ('d50', '🏢 باقة 50 تصميم — مصمم/شركة'), ('d100', '🏢 باقة 100 تصميم — مصمم/شركة')], max_length=20, unique=True),
        ),
    ]
