# Generated by Django 4.2.30 on 2026-06-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0064_relaunch_pricing_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscription',
            name='diag_bot_used_this_period',
            field=models.IntegerField(default=0, verbose_name='أسئلة بوت التشخيص المستهلكة (الفترة الحالية)'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='diag_period_start',
            field=models.DateField(blank=True, null=True, verbose_name='بداية فترة حصة التشخيص الحالية'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='diag_scans_used_this_period',
            field=models.IntegerField(default=0, verbose_name='فحوصات التشخيص المستهلكة (الفترة الحالية)'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='diag_topup_balance',
            field=models.IntegerField(default=0, help_text='استخدامات إضافية فوق حصة الباقة الشهرية، تنزل عند انتهاء الحصة الشهرية.', verbose_name='رصيد شحن التشخيص (استخدامات إضافية)'),
        ),
    ]
