# Generated by Django 4.2.30 on 2026-06-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0065_add_diag_period_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpaymentreceipt',
            name='purchase_type',
            field=models.CharField(choices=[('subscription', 'اشتراك SaaS'), ('parts', 'قطع غيار'), ('design', 'باقة تصاميم'), ('diagnostics', 'ترقية تشخيص'), ('addon', 'إضافة (موظف/فرع/خزينة)'), ('diag_topup', 'شحن تشخيص (30 استخدام)')], db_index=True, max_length=20),
        ),
    ]
