# Generated by Django 4.2.30 on 2026-06-13 10:29

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0069_diagnostics_features_in_catalog'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='escrowhold',
            constraint=models.CheckConstraint(check=models.Q(('held_amount__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('seller_payout_amount'), '+', models.F('buyer_refund_amount')), '+', models.F('platform_commission_amount')))), name='escrowhold_conservation'),
        ),
    ]
