# Generated by Django 4.2.30 on 2026-06-13 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0070_escrowhold_conservation_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('body', models.TextField(verbose_name='نص الرسالة')),
                ('audience', models.CharField(choices=[('all', 'كل الشركات'), ('active', 'الشركات النشطة فقط'), ('trial', 'في الفترة التجريبية'), ('expiring', 'اشتراك ينتهي خلال 14 يوم'), ('at_risk', 'شركات في خطر churn'), ('plan', 'باقة محددة'), ('custom', 'فلتر مخصص')], default='all', max_length=20)),
                ('audience_plan', models.CharField(blank=True, default='', help_text='لو audience=plan: slug الباقة', max_length=20)),
                ('audience_filter', models.JSONField(blank=True, default=dict, help_text='فلتر إضافي JSON (e.g. industry=automotive)')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sending', 'جاري الإرسال'), ('sent', 'تم الإرسال'), ('failed', 'فشل')], db_index=True, default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('audience_size', models.IntegerField(default=0, help_text='عدد المستلمين المتوقع')),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0, help_text='مستلمون بدون بريد')),
                ('error_log', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حملة بث',
                'verbose_name_plural': 'حملات البث',
                'ordering': ['-created_at'],
            },
        ),
    ]
