# Generated by Django 4.2.30 on 2026-06-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0072_broadcast_in_app_banner'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='broadcastdismissal',
            new_name='clients_bro_user_id_52d88f_idx',
            old_name='clients_bro_user_id_campaign_idx',
        ),
    ]
