# Generated by Django 4.2.30 on 2026-09-25 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0080_seed_plan_aed_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="partlisting",
            name="reserved_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reserved_part_listings",
                to="clients.marketplacecustomer",
                verbose_name="محجوزة لمشترٍ محدد",
            ),
        ),
        migrations.AddField(
            model_name="partorder",
            name="shipping_tracking",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="شركة الشحن / رقم التتبع",
            ),
        ),
    ]
