# Generated by Django 4.2.30 on 2026-09-27 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0081_parts_reserved_for_and_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplacePayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payout_code",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("seller_payout", "مستحقات بائع"),
                            ("buyer_refund", "استرداد لمشتري"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار التحويل"),
                            ("paid", "تم التحويل"),
                            ("cancelled", "ملغي"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("method", models.CharField(blank=True, default="", max_length=20)),
                ("account", models.CharField(blank=True, default="", max_length=100)),
                (
                    "account_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="رقم عملية التحويل",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "تحويل مستحقات",
                "verbose_name_plural": "💸 تحويلات مستحقات السوق",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartListingWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_when_saved",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "قطعة محفوظة",
                "verbose_name_plural": "❤ القطع المحفوظة",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="marketplacecustomer",
            name="payout_account",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="رقم المحفظة / عنوان إنستاباي / IBAN",
            ),
        ),
        migrations.AddField(
            model_name="marketplacecustomer",
            name="payout_account_name",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="اسم صاحب الحساب"
            ),
        ),
        migrations.AddField(
            model_name="marketplacecustomer",
            name="payout_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vodafone_cash", "فودافون كاش"),
                    ("instapay", "إنستاباي"),
                    ("bank_transfer", "تحويل بنكي"),
                ],
                default="",
                max_length=20,
                verbose_name="وسيلة استلام الفلوس",
            ),
        ),
        migrations.AddField(
            model_name="partorder",
            name="buyer_rating",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="تقييم المشتري للبائع (1-5)"
            ),
        ),
        migrations.AddField(
            model_name="partorder",
            name="buyer_review",
            field=models.TextField(
                blank=True, default="", verbose_name="تعليق المشتري"
            ),
        ),
        migrations.AddField(
            model_name="partorder",
            name="rated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="partorder",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("buyer_rating__isnull", True),
                    models.Q(("buyer_rating__gte", 1), ("buyer_rating__lte", 5)),
                    _connector="OR",
                ),
                name="partorder_rating_1_to_5",
            ),
        ),
        migrations.AddField(
            model_name="partlistingwatch",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="part_watches",
                to="clients.marketplacecustomer",
            ),
        ),
        migrations.AddField(
            model_name="partlistingwatch",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watches",
                to="clients.partlisting",
            ),
        ),
        migrations.AddField(
            model_name="marketplacepayout",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payouts",
                to="clients.marketplacecustomer",
            ),
        ),
        migrations.AddField(
            model_name="marketplacepayout",
            name="hold",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payouts",
                to="clients.escrowhold",
            ),
        ),
        migrations.AddField(
            model_name="marketplacepayout",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payouts",
                to="clients.partorder",
            ),
        ),
        migrations.AddField(
            model_name="marketplacepayout",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="marketplacepayout",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="marketplace_payouts",
                to="clients.client",
            ),
        ),
        migrations.AddConstraint(
            model_name="partlistingwatch",
            constraint=models.UniqueConstraint(
                fields=("customer", "listing"), name="partwatch_one_per_customer"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacepayout",
            index=models.Index(
                fields=["status", "-created_at"], name="clients_mar_status_f07ef9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketplacepayout",
            constraint=models.UniqueConstraint(
                fields=("hold", "kind"), name="payout_one_per_hold_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketplacepayout",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)), name="payout_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketplacepayout",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("customer__isnull", False), ("tenant__isnull", True)),
                    models.Q(("customer__isnull", True), ("tenant__isnull", False)),
                    _connector="OR",
                ),
                name="payout_one_recipient",
            ),
        ),
    ]
