# Generated by Django 4.2.30 on 2026-06-03 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0018_backfill_employee_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='توكن الجهاز')),
                ('hardware_id', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_devices', to='inventory.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'جهاز فحص OBD',
                'verbose_name_plural': '🔌 أجهزة الفحص الميدانية',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('live_obd', 'Live OBD device'), ('manual', 'إدخال يدوي'), ('api', 'REST API')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('blocked_quota', 'تم الحجب — نفدت الحصة'), ('blocked_subscription', 'تم الحجب — اشتراك غير مفعّل'), ('error', 'خطأ')], default='in_progress', max_length=25)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='smart_diagnostics.diagnosticdevice')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_scans', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_scans', to='inventory.vehicle')),
            ],
            options={
                'verbose_name': 'جلسة فحص تشخيصي',
                'verbose_name_plural': '🩺 جلسات الفحص التشخيصي',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestPlanExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtc_code', models.CharField(db_index=True, max_length=8)),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('in_progress', 'قيد التنفيذ'), ('passed', 'نجح'), ('failed', 'فشل'), ('aborted', 'ألغي')], default='pending', max_length=15)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('final_conclusion', models.TextField(blank=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='smart_diagnostics.diagnosticscan')),
            ],
            options={
                'verbose_name': 'تنفيذ خطة فحص',
                'verbose_name_plural': '🧪 Interactive Test Plans',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('provider', models.CharField(max_length=30)),
                ('endpoint', models.CharField(max_length=80)),
                ('dtc_code', models.CharField(blank=True, max_length=8)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('cache_hit', models.BooleanField(default=False, help_text='True = served من cache، مفيش تكلفة')),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل مكالمة API',
                'verbose_name_plural': '💰 API Call Cost Log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TestStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('action', models.TextField(blank=True)),
                ('expected', models.TextField(blank=True)),
                ('technician_observation', models.TextField(blank=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='smart_diagnostics.testplanexecution')),
            ],
            options={
                'ordering': ['execution', 'step_number'],
                'unique_together': {('execution', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='LiveTelemetryFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('rpm', models.IntegerField(blank=True, null=True)),
                ('engine_load_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coolant_temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intake_temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vehicle_speed_kph', models.IntegerField(blank=True, null=True)),
                ('throttle_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('battery_v', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_frames', to='smart_diagnostics.diagnosticscan')),
            ],
            options={
                'verbose_name': 'إطار قياس حي',
                'verbose_name_plural': '📊 Live Telemetry Frames',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['scan', '-timestamp'], name='smart_diagn_scan_id_a24958_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtc_code', models.CharField(db_index=True, max_length=8, verbose_name='كود العطل')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mileage_at_detection', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(default='medium', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('resolution_note', models.TextField(blank=True, verbose_name='ملاحظات الحل')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_faults', to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faults', to='smart_diagnostics.diagnosticscan')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_history', to='inventory.vehicle')),
            ],
            options={
                'verbose_name': 'سجل عطل',
                'verbose_name_plural': '📖 الجواز الصحي للمركبة (Fault History)',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['vehicle', 'dtc_code', '-detected_at'], name='smart_diagn_vehicle_456749_idx'), models.Index(fields=['resolved_at'], name='smart_diagn_resolve_a72c9b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='diagnosticscan',
            index=models.Index(fields=['vehicle', '-started_at'], name='smart_diagn_vehicle_840bee_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticscan',
            index=models.Index(fields=['status'], name='smart_diagn_status_776cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['provider', '-timestamp'], name='smart_diagn_provide_145dec_idx'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['cache_hit'], name='smart_diagn_cache_h_0b3faa_idx'),
        ),
    ]
