# Generated by Django 4.2.30 on 2026-06-03 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_backfill_employee_is_staff'),
        ('smart_diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticdevice',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='اتركها فارغة لأجهزة الورشة المحمولة (ELM327 وأمثاله).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_devices', to='inventory.vehicle', verbose_name='المركبة (اختياري — للأجهزة المثبتة دائماً)'),
        ),
    ]
