# Generated by Django 4.2.30 on 2026-05-16 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفرع')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='الموقع')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم تليفون الفرع')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('chassis_number', models.CharField(blank=True, max_length=17, null=True, verbose_name='رقم الشاسيه (VIN) للسيارة الأساسية')),
                ('car_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم اللوحة')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الرصيد / المديونية')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'سجل العملاء (CRM)',
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='بند المصروف')),
            ],
            options={
                'verbose_name_plural': 'بنود المصروفات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القطعة')),
                ('part_number', models.CharField(max_length=100, unique=True, verbose_name='Part Number')),
                ('brand', models.CharField(default='BMW', max_length=100, verbose_name='الماركة')),
                ('engine_code', models.CharField(blank=True, max_length=100, verbose_name='كود المحرك')),
                ('car_model', models.CharField(max_length=100, verbose_name='الموديلات المتوافقة')),
                ('car_year', models.CharField(max_length=100, verbose_name='سنة الصنع')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='الباركود')),
                ('min_stock_level', models.IntegerField(default=2, verbose_name='حد التنبيه (أقل كمية)')),
                ('shopify_product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shopify ID')),
                ('warranty_months', models.IntegerField(default=0, verbose_name='فترة الضمان (بالأشهر)')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='آخر سعر شراء')),
                ('retail_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر البيع')),
                ('average_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='متوسط التكلفة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة القطعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المدفوع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'تم الاستلام (مقفولة)')], default='draft', max_length=20, verbose_name='الحالة')),
                ('is_applied', models.BooleanField(default=False, editable=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.branch', verbose_name='فرع الاستلام')),
            ],
        ),
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('sale', 'بيع فقط'), ('maintenance', 'صيانة وقطع غيار')], max_length=20, verbose_name='النوع')),
                ('status', models.CharField(choices=[('draft', 'مسودة مفتوحة'), ('posted', 'معتمدة ومقفولة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('mileage', models.IntegerField(blank=True, null=True, verbose_name='قراءة العداد (كم)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='موعد الصيانة القادمة')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مصنعية')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='خصم')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='ضريبة %')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الإجمالي النهائي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المدفوع (عربون/كاش)')),
                ('is_applied', models.BooleanField(default=False, editable=False)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.branch', verbose_name='الفرع')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.customer', verbose_name='العميل (البحث بالاسم أو الرقم)')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المورد / الشركة')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('company_details', models.TextField(blank=True, null=True, verbose_name='تفاصيل الشركة / العنوان')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='حساب المورد (مستحقاته)')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'سجل الموردين (SRM)',
            },
        ),
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخزنة/الحساب')),
                ('type', models.CharField(choices=[('cash', 'كاش'), ('bank', 'حساب بنكي'), ('visa', 'فيزا'), ('wallet', 'محفظة')], default='cash', max_length=20, verbose_name='النوع')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الرصيد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasuries', to='inventory.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'خزنة / حساب',
                'verbose_name_plural': 'الخزائن والحسابات',
                'unique_together': {('name', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('date_transferred', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'تم التحويل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='inventory.branch', verbose_name='من فرع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='القطعة')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='inventory.branch', verbose_name='إلى فرع')),
            ],
        ),
        migrations.CreateModel(
            name='SaleInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع')),
                ('cost_at_sale', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.saleinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.treasury', verbose_name='الدفع على خزنة'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='الكمية')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.treasury', verbose_name='الدفع من خزنة'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.vendor', verbose_name='المورد'),
        ),
        migrations.CreateModel(
            name='HistoricalTreasury',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخزنة/الحساب')),
                ('type', models.CharField(choices=[('cash', 'كاش'), ('bank', 'حساب بنكي'), ('visa', 'فيزا'), ('wallet', 'محفظة')], default='cash', max_length=20, verbose_name='النوع')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الرصيد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.branch', verbose_name='الفرع')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical خزنة / حساب',
                'verbose_name_plural': 'historical الخزائن والحسابات',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStockTransfer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('date_transferred', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'تم التحويل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('from_branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.branch', verbose_name='من فرع')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='القطعة')),
                ('to_branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.branch', verbose_name='إلى فرع')),
            ],
            options={
                'verbose_name': 'historical stock transfer',
                'verbose_name_plural': 'historical stock transfers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القطعة')),
                ('part_number', models.CharField(db_index=True, max_length=100, verbose_name='Part Number')),
                ('brand', models.CharField(default='BMW', max_length=100, verbose_name='الماركة')),
                ('engine_code', models.CharField(blank=True, max_length=100, verbose_name='كود المحرك')),
                ('car_model', models.CharField(max_length=100, verbose_name='الموديلات المتوافقة')),
                ('car_year', models.CharField(max_length=100, verbose_name='سنة الصنع')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='الباركود')),
                ('min_stock_level', models.IntegerField(default=2, verbose_name='حد التنبيه (أقل كمية)')),
                ('shopify_product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shopify ID')),
                ('warranty_months', models.IntegerField(default=0, verbose_name='فترة الضمان (بالأشهر)')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='آخر سعر شراء')),
                ('retail_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر البيع')),
                ('average_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='متوسط التكلفة')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='صورة القطعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical product',
                'verbose_name_plural': 'historical products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFinancialTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'إيداع / إيراد'), ('out', 'سحب / مصروف')], max_length=10, verbose_name='النوع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.expensecategory', verbose_name='البند')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.customer', verbose_name='دفعة من عميل')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.purchaseinvoice', verbose_name='فاتورة شراء')),
                ('sale_invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.saleinvoice', verbose_name='فاتورة بيع')),
                ('treasury', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.treasury', verbose_name='الخزنة')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.vendor', verbose_name='دفعة لمورد')),
            ],
            options={
                'verbose_name': 'historical financial transaction',
                'verbose_name_plural': 'historical الخزينة (حركات مالية)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'إيداع / إيراد'), ('out', 'سحب / مصروف')], max_length=10, verbose_name='النوع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.expensecategory', verbose_name='البند')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customer', verbose_name='دفعة من عميل')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='inventory.purchaseinvoice', verbose_name='فاتورة شراء')),
                ('sale_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='inventory.saleinvoice', verbose_name='فاتورة بيع')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.treasury', verbose_name='الخزنة')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor', verbose_name='دفعة لمورد')),
            ],
            options={
                'verbose_name_plural': 'الخزينة (حركات مالية)',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدير عام (أدمن)'), ('manager', 'مدير فرع'), ('cashier', 'كاشير / استقبال'), ('tech', 'فني / أمين مخزن')], default='cashier', max_length=20, verbose_name='الدور الوظيفي')),
                ('can_edit_posted_invoices', models.BooleanField(default=False, verbose_name='صلاحية تعديل الفواتير المعتمدة؟')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.branch', verbose_name='الفرع التابع له')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف الموظف',
                'verbose_name_plural': 'ملفات الموظفين والصلاحيات',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='الكمية المتاحة')),
                ('shelf_location', models.CharField(blank=True, max_length=50, null=True, verbose_name='مكان الرف')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.branch', verbose_name='الفرع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='القطعة')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'unique_together': {('product', 'branch')},
            },
        ),
    ]
