# Generated by Django 4.2.30 on 2026-05-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='car_plate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='chassis_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(default=0, verbose_name='نقاط الولاء (المكافآت)'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='is_return',
            field=models.BooleanField(default=False, verbose_name='فاتورة مرتجع؟'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='قراءة العداد الحالية (كم)'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_number', models.CharField(max_length=17, unique=True, verbose_name='رقم الشاسيه (VIN)')),
                ('car_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم اللوحة')),
                ('brand', models.CharField(default='BMW', max_length=50, verbose_name='ماركة السيارة')),
                ('model_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='الموديل (مثال: 320i)')),
                ('last_mileage', models.IntegerField(default=0, verbose_name='آخر قراءة للعداد (كم)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='inventory.customer', verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'مركبة',
                'verbose_name_plural': 'سجل المركبات',
            },
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vehicle', verbose_name='المركبة (اختياري للبيع المباشر)'),
        ),
    ]
