# Generated by Django 4.2.30 on 2026-05-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_customer_car_plate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخدمة / الصيانة')),
                ('labor_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر المصنعية الثابت')),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='الوقت التقديري (ساعات)')),
                ('tech_commission_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة عمولة الفني %')),
            ],
            options={
                'verbose_name': 'خدمة صيانة',
                'verbose_name_plural': 'كتالوج الخدمات والمصنعيات',
            },
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='labor_cost',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='next_visit_date',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='commission_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='رصيد العمولات المستحقة'),
        ),
        migrations.AddField(
            model_name='product',
            name='alternatives',
            field=models.ManyToManyField(blank=True, to='inventory.product', verbose_name='البدائل المتوافقة (لو الصنف خلص)'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='labor_cost_manual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مصنعية إضافية (يدوي)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='estimated_next_visit',
            field=models.DateField(blank=True, null=True, verbose_name='موعد الصيانة المتوقع'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(default=0, verbose_name='نقاط الولاء'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير عام (أدمن)'), ('manager', 'مدير فرع'), ('cashier', 'كاشير / استقبال'), ('tech', 'فني / ميكانيكي'), ('stock', 'أمين مخزن')], default='cashier', max_length=20, verbose_name='الدور الوظيفي'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='خصم إجمالي'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('sale', 'بيع قطع غيار'), ('maintenance', 'صيانة شاملة')], max_length=20, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات وشكوى العميل'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المدفوع'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'جاري العمل (ورشة)'), ('posted', 'معتمدة وتم التسليم')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.treasury', verbose_name='سداد على خزنة'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vehicle', verbose_name='المركبة'),
        ),
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brakes_status', models.CharField(choices=[('green', 'ممتاز (أخضر)'), ('yellow', 'يحتاج متابعة (أصفر)'), ('red', 'تغيير فوري (أحمر)')], default='green', max_length=10, verbose_name='حالة تيل وطنابير الفرامل')),
                ('engine_oil_status', models.CharField(choices=[('green', 'ممتاز (أخضر)'), ('yellow', 'يحتاج متابعة (أصفر)'), ('red', 'تغيير فوري (أحمر)')], default='green', max_length=10, verbose_name='زيت المحرك')),
                ('tires_status', models.CharField(choices=[('green', 'ممتاز (أخضر)'), ('yellow', 'يحتاج متابعة (أصفر)'), ('red', 'تغيير فوري (أحمر)')], default='green', max_length=10, verbose_name='حالة الإطارات')),
                ('battery_status', models.CharField(choices=[('green', 'ممتاز (أخضر)'), ('yellow', 'يحتاج متابعة (أصفر)'), ('red', 'تغيير فوري (أحمر)')], default='green', max_length=10, verbose_name='كفاءة البطارية')),
                ('technician_notes', models.TextField(blank=True, verbose_name='ملاحظات الفني الحرجة للعميل')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_report', to='inventory.saleinvoice', verbose_name='أمر الشغل')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vehicle', verbose_name='السيارة')),
            ],
            options={
                'verbose_name': 'فحص رقمي 21 نقطة',
            },
        ),
        migrations.CreateModel(
            name='SaleInvoiceServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة المصنعية')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='inventory.saleinvoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.servicecatalog', verbose_name='الخدمة المنفذة')),
                ('technician', models.ForeignKey(blank=True, limit_choices_to={'role': 'tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.employeeprofile', verbose_name='الفني المنفذ')),
            ],
        ),
    ]
