# Generated by Django 4.2.30 on 2026-05-16 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_servicecatalog_remove_saleinvoice_labor_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleinspection',
            options={'verbose_name': 'فحص رقمي مرئي 21 نقطة'},
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الشركة (لعملاء الـ B2B)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='core_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قيمة التالف/الكور (مستردة للعميل)'),
        ),
        migrations.AddField(
            model_name='product',
            name='core_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قيمة التالف/الكور (مستردة للعميل)'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='invoice_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='saleinvoiceserviceitem',
            name='actual_hours',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='ساعات العمل الفعلية'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='لون السيارة'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Auto', 'أوتوماتيك'), ('Manual', 'مانيوال')], default='Auto', max_length=20, verbose_name='نوع الفتيس'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='inspections/', verbose_name='صورة مرفقة (للقطع التالفة)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='ضريبة القيمة المضافة %'),
        ),
    ]
