# Generated by Django 4.2.30 on 2026-05-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_vehicleinspection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinvoice',
            name='invoice_uuid',
        ),
    ]
