# Generated by Django 4.2.30 on 2026-05-17 11:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_saleinvoice_invoice_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapDismantlingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_ref', models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='كود عملية التقطيع')),
                ('car_model', models.CharField(max_length=100, verbose_name='موديل سيارة التقطيع (مثال: نص أمامي F30)')),
                ('chassis_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الشاسيه الأصلي')),
                ('total_purchase_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='تكلفة الشراء والاستيراد الكلية')),
                ('customs_doc', models.FileField(blank=True, null=True, upload_to='customs_docs/', verbose_name='مستندات الإفراج الجمركي (PDF)')),
                ('engine_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المحرك المفرج عنه')),
                ('date_dismantled', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التفكيك')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تم التفكيك والتسعير')),
            ],
            options={
                'verbose_name': 'عملية تقطيع / استيراد',
                'verbose_name_plural': '🚢 محرك التفكيك والإفراج الجمركي',
            },
        ),
        migrations.AlterModelOptions(
            name='vehicleinspection',
            options={'verbose_name': 'فحص رقمي وتوثيق مرئي'},
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='condition',
            field=models.CharField(choices=[('new', 'جديد'), ('used', 'استيراد/تقطيع'), ('core', 'تالف للتجديد')], default='new', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='is_b2b_published',
            field=models.BooleanField(default=False, verbose_name='طرح في سوق Mouss Tec العام'),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'جديد'), ('used', 'استيراد/تقطيع'), ('core', 'تالف للتجديد')], default='new', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_b2b_published',
            field=models.BooleanField(default=False, verbose_name='طرح في سوق Mouss Tec العام'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='bidding_ref',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مرجع المزاد المالي (Escrow)'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='is_b2b_secured',
            field=models.BooleanField(default=False, verbose_name='شراء آمن عبر Mouss Tec'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='total_core_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='إجمالي التوالف المستحقة'),
        ),
        migrations.AddField(
            model_name='saleinvoiceitem',
            name='core_charge_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleinvoiceitem',
            name='is_core_returned',
            field=models.BooleanField(default=False, verbose_name='تم استلام القطعة التالفة؟'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='inspection_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='بصمة زمنية للفحص'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الشركة (B2B)'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='core_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تأمين التالف/الكور (يُسترد للعميل)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alternatives',
            field=models.ManyToManyField(blank=True, to='inventory.product', verbose_name='البدائل المتوافقة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='core_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تأمين التالف/الكور (يُسترد للعميل)'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='labor_cost_manual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مصنعية إضافية'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='قراءة العداد (كم)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='inspections/', verbose_name='صورة إثبات التلف'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='battery_status',
            field=models.CharField(choices=[('green', 'ممتاز'), ('yellow', 'يحتاج متابعة'), ('red', 'تغيير فوري')], default='green', max_length=10, verbose_name='البطارية'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='brakes_status',
            field=models.CharField(choices=[('green', 'ممتاز'), ('yellow', 'يحتاج متابعة'), ('red', 'تغيير فوري')], default='green', max_length=10, verbose_name='الفرامل'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='engine_oil_status',
            field=models.CharField(choices=[('green', 'ممتاز'), ('yellow', 'يحتاج متابعة'), ('red', 'تغيير فوري')], default='green', max_length=10, verbose_name='زيت المحرك'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='technician_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الفني'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='tires_status',
            field=models.CharField(choices=[('green', 'ممتاز'), ('yellow', 'يحتاج متابعة'), ('red', 'تغيير فوري')], default='green', max_length=10, verbose_name='الإطارات'),
        ),
    ]
