# Generated by Django 4.2.30 on 2026-05-17 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_scrapdismantlingjob_alter_vehicleinspection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapdismantlingjob',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.branch', verbose_name='فرع التخزين'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ai_health_score',
            field=models.IntegerField(default=100, verbose_name='مؤشر صحة المركبة بالـ AI (%)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='predicted_failure_notes',
            field=models.TextField(blank=True, null=True, verbose_name='الأعطال المتوقعة قريباً (AI)'),
        ),
        migrations.AlterField(
            model_name='scrapdismantlingjob',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='تم التفكيك (إضافة للمخزن)'),
        ),
        migrations.CreateModel(
            name='ScrapDismantlingYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='الكمية المستخرجة')),
                ('estimated_cost_allocation', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة التقديرية المحملة للقطعة')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yields', to='inventory.scrapdismantlingjob')),
                ('product', models.ForeignKey(limit_choices_to={'condition': 'used'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='القطعة المستخرجة')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_retail', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_retail', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.product')),
            ],
            options={
                'verbose_name_plural': 'سجل تاريخ الأسعار',
            },
        ),
    ]
