# Generated by Django 4.2.30 on 2026-05-17 18:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_scrapdismantlingjob_branch_vehicle_ai_health_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'عميل / شركة', 'verbose_name_plural': 'سجل العملاء والشركات (CRM)'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_b2b_company',
            field=models.BooleanField(default=False, verbose_name='حساب شركة (B2B Fleet)'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='currency',
            field=models.CharField(choices=[('EGP', 'جنية مصري'), ('AED', 'درهم إماراتي'), ('USD', 'دولار أمريكي')], default='EGP', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='سعر الصرف وقت العملية'),
        ),
        migrations.AddField(
            model_name='historicalfinancialtransaction',
            name='currency',
            field=models.CharField(choices=[('EGP', 'جنية مصري'), ('AED', 'درهم إماراتي'), ('USD', 'دولار أمريكي')], default='EGP', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='historicalfinancialtransaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='سعر الصرف وقت العملية'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='ai_calculated_min_stock',
            field=models.IntegerField(default=2, verbose_name='حد التنبيه الديناميكي (AI)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='ai_suggested_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر السوق المقترح (AI)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='b2b_wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر البيع (جملة/B2B)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_calculated_min_stock',
            field=models.IntegerField(default=2, verbose_name='حد التنبيه الديناميكي (AI)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_suggested_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر السوق المقترح (AI)'),
        ),
        migrations.AddField(
            model_name='product',
            name='b2b_wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر البيع (جملة/B2B)'),
        ),
        migrations.AddField(
            model_name='saleinvoiceitem',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الضمان'),
        ),
        migrations.AddField(
            model_name='saleinvoiceserviceitem',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='نهاية العمل الفعلي'),
        ),
        migrations.AddField(
            model_name='saleinvoiceserviceitem',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='بداية العمل الفعلي'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم العميل أو الشركة'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ (بالعملة المحلية)'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ (بالعملة المحلية)'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='core_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تأمين التالف/الكور'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='min_stock_level',
            field=models.IntegerField(default=2, verbose_name='حد التنبيه الأساسي'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر البيع (قطاعي)'),
        ),
        migrations.AlterField(
            model_name='historicalstocktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_transit', 'في الطريق'), ('completed', 'تم الاستلام'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='historicaltreasury',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الرصيد الأساسي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='core_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تأمين التالف/الكور'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_level',
            field=models.IntegerField(default=2, verbose_name='حد التنبيه الأساسي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر البيع (قطاعي)'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='labor_cost_manual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مصنعية إضافية عامة'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='status',
            field=models.CharField(choices=[('quotation', 'عرض سعر (مسودة)'), ('in_progress', 'قيد العمل بالورشة'), ('quality_check', 'فحص الجودة (QA)'), ('ready', 'جاهز للتسليم'), ('posted', 'تم التسليم والاعتماد')], default='quotation', max_length=20, verbose_name='الحالة التشغيلية'),
        ),
        migrations.AlterField(
            model_name='saleinvoiceserviceitem',
            name='actual_hours',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='ساعات العمل المُباعة'),
        ),
        migrations.AlterField(
            model_name='scrapdismantlingjob',
            name='car_model',
            field=models.CharField(max_length=100, verbose_name='موديل سيارة التقطيع'),
        ),
        migrations.AlterField(
            model_name='scrapdismantlingyield',
            name='estimated_cost_allocation',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة التقديرية للقطعة'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_transit', 'في الطريق'), ('completed', 'تم الاستلام'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الرصيد الأساسي'),
        ),
        migrations.CreateModel(
            name='VehicleTelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtc_codes_found', models.CharField(blank=True, max_length=255, null=True, verbose_name='أكواد الأعطال المرصودة')),
                ('battery_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='فولتية البطارية')),
                ('raw_json_data', models.JSONField(blank=True, null=True, verbose_name='البيانات الخام من جهاز الفحص')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to='inventory.vehicle')),
            ],
            options={
                'verbose_name_plural': 'سجل الفحوصات الرقمية الحية (IoT)',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='بداية العقد')),
                ('end_date', models.DateField(verbose_name='نهاية العقد')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة العقد السنوية')),
                ('is_active', models.BooleanField(default=True, verbose_name='ساري المفعول')),
                ('customer', models.ForeignKey(limit_choices_to={'is_b2b_company': True}, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='inventory.customer')),
            ],
            options={
                'verbose_name_plural': 'عقود صيانة الشركات (B2B)',
            },
        ),
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت تسجيل الدخول')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='وقت تسجيل الخروج')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='إجمالي ساعات الوردية')),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'tech'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.employeeprofile', verbose_name='الفني')),
            ],
            options={
                'verbose_name_plural': 'سجل حضور وإنتاجية الفنيين',
            },
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='maintenance_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.maintenancecontract', verbose_name='مخصوم من عقد الصيانة'),
        ),
    ]
