# Generated by Django 4.2.30 on 2026-05-23 12:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_seed_expense_categories_force'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountingentry',
            new_name='inventory_a_referen_00b615_idx',
            old_name='inventory_ae_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='accountingentry',
            new_name='inventory_a_account_4e8fcb_idx',
            old_name='inventory_ae_acc_date_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='inventory_a_model_n_740003_idx',
            old_name='inventory_a_model_n_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='inventory_a_timesta_f11ce6_idx',
            old_name='inventory_a_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inventory_i_product_d7930e_idx',
            old_name='inventory_im_prod_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inventory_i_branch__305656_idx',
            old_name='inventory_im_branch_idx',
        ),
        migrations.AddField(
            model_name='historicalfinancialtransaction',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.employeeprofile', verbose_name='الموظف (للرواتب/السلف)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='ai_price_elasticity',
            field=models.DecimalField(decimal_places=2, default=1.0, editable=False, max_digits=4),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='chassis_compatibility',
            field=models.JSONField(blank=True, help_text="أكواد الشاسيهات المتوافقة (مثال: ['F30', 'E90', 'G20'])", null=True, verbose_name='توافقية الشاسيه'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='oem_cross_reference',
            field=models.JSONField(blank=True, help_text='أرقام الـ OEM البديلة المطابقة', null=True, verbose_name='أكواد الأجزاء البديلة'),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_price_elasticity',
            field=models.DecimalField(decimal_places=2, default=1.0, editable=False, max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='chassis_compatibility',
            field=models.JSONField(blank=True, help_text="أكواد الشاسيهات المتوافقة (مثال: ['F30', 'E90', 'G20'])", null=True, verbose_name='توافقية الشاسيه'),
        ),
        migrations.AddField(
            model_name='product',
            name='oem_cross_reference',
            field=models.JSONField(blank=True, help_text='أرقام الـ OEM البديلة المطابقة', null=True, verbose_name='أكواد الأجزاء البديلة'),
        ),
        migrations.AddField(
            model_name='vehicletelemetrylog',
            name='requires_immediate_attention',
            field=models.BooleanField(default=False, verbose_name='تحذير: عطل حرج يتطلب تدخلاً فورياً'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='سعر الشراء يجب أن يكون أكبر من صفر')], verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='الكمية يجب أن تكون 1 على الأقل')], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='status',
            field=models.CharField(choices=[('quotation', 'عرض سعر (مسودة)'), ('in_progress', 'قيد العمل بالمركز'), ('quality_check', 'فحص الجودة (QA)'), ('ready', 'جاهز للتسليم'), ('posted', 'تم التسليم والاعتماد')], default='quotation', max_length=20, verbose_name='الحالة التشغيلية'),
        ),
        migrations.AlterField(
            model_name='saleinvoiceitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='الكمية يجب أن تكون 1 على الأقل')], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='saleinvoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='السعر لا يمكن أن يكون سالباً')], verbose_name='سعر البيع'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='inventory_quantity_non_negative'),
        ),
    ]
