# Generated by Django 4.2.30 on 2026-05-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rename_inventory_ae_ref_idx_inventory_a_referen_00b615_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoiceserviceitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='اتركه فارغاً ليتم ملؤه تلقائياً من كتالوج الخدمات', max_digits=10, null=True, verbose_name='قيمة المصنعية'),
        ),
    ]
