# Generated by Django 4.2.30 on 2026-05-29 07:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0015_fix_service_item_price_and_accounting_entry_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(verbose_name='تاريخ الكشف')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد الافتتاحي')),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد الختامي')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='bank_statements/%Y/%m/')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='تمت المطابقة')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='inventory.treasury', verbose_name='الخزينة / الحساب البنكي')),
            ],
            options={
                'verbose_name': 'كشف بنكي',
                'verbose_name_plural': '🏦 كشوف البنوك',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='مرجع البنك')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('direction', models.CharField(choices=[('debit', 'سحب (مدين)'), ('credit', 'إيداع (دائن)')], max_length=10)),
                ('match_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0-100 — ثقة المطابقة التلقائية', max_digits=5)),
                ('is_matched', models.BooleanField(db_index=True, default=False)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_lines', to='inventory.financialtransaction', verbose_name='الحركة المالية المطابقة')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.bankstatement')),
            ],
            options={
                'verbose_name': 'سطر كشف بنكي',
                'verbose_name_plural': 'سطور كشوف البنوك',
                'ordering': ['transaction_date', 'pk'],
                'indexes': [models.Index(fields=['statement', 'is_matched'], name='inventory_b_stateme_cd4b6f_idx'), models.Index(fields=['transaction_date', 'amount'], name='inventory_b_transac_8b0911_idx')],
            },
        ),
    ]
