# Generated by Django 4.2.30 on 2026-05-30 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0016_add_bank_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_invoices', to='inventory.saleinvoice', verbose_name='الفاتورة الأصلية (للمرتجع)'),
        ),
        migrations.CreateModel(
            name='B2BListingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('requested_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر المطلوب')),
                ('approved_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر المعتمد')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_synced', models.BooleanField(default=False, editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_listing_requests', to='inventory.product', verbose_name='المنتج')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='طالب النشر')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='المراجع')),
            ],
            options={
                'verbose_name': 'طلب نشر في السوق',
                'verbose_name_plural': 'طلبات النشر في السوق المركزي (B2B)',
                'ordering': ['-created_at'],
            },
        ),
    ]
