# Generated by Django 4.2.30 on 2026-06-04 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_backfill_employee_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=160, verbose_name='عنوان المهمة')),
                ('tech_notes', models.TextField(blank=True, verbose_name='ملاحظات فنية')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت البدء')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('paused_seconds', models.IntegerField(default=0, verbose_name='ثوانٍ توقف')),
                ('last_paused_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('open', 'قيد التنفيذ'), ('paused', 'متوقف مؤقتاً'), ('done', 'مكتمل'), ('blocked', 'بانتظار قطع إضافية')], default='open', max_length=12, verbose_name='الحالة')),
                ('needs_extra_parts', models.BooleanField(default=False, verbose_name='يحتاج قطع إضافية؟')),
                ('extra_parts_note', models.TextField(blank=True, verbose_name='تفاصيل القطع المطلوبة')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_logs', to='inventory.saleinvoice', verbose_name='بطاقة الإصلاح')),
            ],
            options={
                'verbose_name': 'سجل إصلاح',
                'verbose_name_plural': 'سجلات الإصلاح (Tech)',
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='can_see_costs',
            field=models.BooleanField(default=False, help_text='Sales = False بشكل افتراضي — يرى أسعار البيع فقط', verbose_name='صلاحية رؤية أسعار التكلفة؟'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='commission_rate_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='تُطبَّق على هامش الربح للقطع التي يبيعها الموظف', max_digits=5, verbose_name='نسبة عمولة المبيعات %'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='last_checkin_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تسجيل حضور'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='last_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='آخر Lat'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='last_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='آخر Lng'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='system_key',
            field=models.CharField(blank=True, choices=[('salaries', 'رواتب وأجور'), ('rent', 'إيجار'), ('utilities', 'مرافق'), ('other', 'أخرى')], db_index=True, help_text="مفتاح ثابت للتعرف الآلي — مثلاً 'salaries' يفعّل قائمة الموظفين تلقائياً", max_length=30, verbose_name='مفتاح النظام'),
        ),
        migrations.AddField(
            model_name='saleinvoiceitem',
            name='commission_accrued',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='العمولة المُحتسبة'),
        ),
        migrations.AddField(
            model_name='saleinvoiceitem',
            name='salesperson',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['sales', 'cashier', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_items', to='inventory.employeeprofile', verbose_name='بائع القطعة (للعمولة)'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير عام (أدمن)'), ('manager', 'مدير فرع'), ('sales', 'مبيعات (Sales)'), ('engineer', 'مهندس تشخيص (Engineer)'), ('tech', 'فني / ميكانيكي (Technician)'), ('cashier', 'كاشير / استقبال (Cashier)'), ('stock', 'أمين مخزن'), ('hr', 'موارد بشرية (HR)')], default='cashier', max_length=20, verbose_name='الدور الوظيفي'),
        ),
        migrations.CreateModel(
            name='RepairLogMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('before', 'قبل الإصلاح'), ('after', 'بعد الإصلاح'), ('issue', 'مشكلة/تحذير')], default='before', max_length=10, verbose_name='النوع')),
                ('image', models.ImageField(upload_to='repair_logs/%Y/%m/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='تعليق')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='inventory.repairlog')),
            ],
            options={
                'verbose_name': 'مرفق سجل إصلاح',
                'verbose_name_plural': 'مرفقات سجلات الإصلاح',
            },
        ),
        migrations.AddField(
            model_name='repairlog',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role__in': ['tech', 'engineer']}, on_delete=django.db.models.deletion.PROTECT, related_name='repair_logs', to='inventory.employeeprofile', verbose_name='الفني'),
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='رمز الرابط العام')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='ملاحظات العميل')),
                ('received_in_good_condition', models.BooleanField(default=False, verbose_name='استلمت السيارة بحالة جيدة')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/', verbose_name='توقيع رقمي')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('sale_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='inventory.saleinvoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'تقييم وتوقيع عميل',
                'verbose_name_plural': 'تقييمات وتوقيعات العملاء',
            },
        ),
        migrations.CreateModel(
            name='AttendanceCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('in', 'حضور'), ('out', 'انصراف')], default='in', max_length=5, verbose_name='النوع')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='اللحظة الزمنية')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('accuracy_m', models.FloatField(blank=True, null=True, verbose_name='دقة GPS (متر)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('is_inside_geofence', models.BooleanField(default=False, verbose_name='داخل حدود الفرع؟')),
                ('flagged_reason', models.CharField(blank=True, max_length=120, verbose_name='سبب التنبيه')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='inventory.employeeprofile', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'حركة حضور',
                'verbose_name_plural': 'سجل الحضور والانصراف (GPS)',
            },
        ),
        migrations.CreateModel(
            name='VehicleDiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('pre_repair', 'فحص قبل الإصلاح'), ('post_repair', 'فحص بعد الإصلاح / تأكيد جودة'), ('ad_hoc', 'فحص خارجي')], max_length=20, verbose_name='نوع الفحص')),
                ('scanned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='وقت الفحص')),
                ('fault_codes', models.JSONField(blank=True, default=list, help_text="مصفوفة مثل: ['P0171', 'P0300']", verbose_name='أكواد الأعطال (DTCs)')),
                ('live_data', models.JSONField(blank=True, default=dict, help_text='RPM, coolant_temp_c, maf_gs, ...', verbose_name='القراءات الحية (PIDs)')),
                ('device_id', models.CharField(blank=True, max_length=80, verbose_name='معرّف جهاز المسح')),
                ('raw_payload', models.JSONField(blank=True, default=dict, editable=False)),
                ('severity_score', models.IntegerField(default=0, verbose_name='درجة الخطورة (0-100)')),
                ('engineer', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['engineer', 'tech']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_reports', to='inventory.employeeprofile', verbose_name='المهندس / الفني')),
                ('job_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_reports', to='inventory.saleinvoice', verbose_name='بطاقة الإصلاح المرتبطة')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_reports', to='inventory.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'تقرير OBD',
                'verbose_name_plural': 'تقارير OBD التشخيصية',
                'indexes': [models.Index(fields=['vehicle', '-scanned_at'], name='inventory_v_vehicle_7ce863_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='repairlog',
            index=models.Index(fields=['job_card', '-started_at'], name='inventory_r_job_car_1ac270_idx'),
        ),
        migrations.AddIndex(
            model_name='repairlog',
            index=models.Index(fields=['technician', 'status'], name='inventory_r_technic_aa04b7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancecheckin',
            index=models.Index(fields=['employee', '-occurred_at'], name='inventory_a_employe_5f50e8_idx'),
        ),
    ]
