# Generated by Django 4.2.30 on 2026-06-06 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0020_backfill_salary_system_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDiagnosticPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=inventory.models._diag_photo_upload_path, verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=240, verbose_name='وصف مختصر')),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='وقت الرفع')),
            ],
            options={
                'verbose_name': 'صورة تشخيص',
                'verbose_name_plural': 'صور التشخيص',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='vehiclediagnosticreport',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='التحليل النهائي اللي هيشوفه مستشار الخدمة والعميل.', verbose_name='ملخص تحليل الذكاء الاصطناعي'),
        ),
        migrations.AddField(
            model_name='vehiclediagnosticreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_reports_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه'),
        ),
        migrations.AddField(
            model_name='vehiclediagnosticreport',
            name='source',
            field=models.CharField(choices=[('mobile_ingest', 'OBD مباشر من الموبايل'), ('diag_room', 'غرفة تشخيص الأعطال (Web Bluetooth)')], default='mobile_ingest', max_length=20, verbose_name='مصدر التقرير'),
        ),
        migrations.AddField(
            model_name='vehiclediagnosticreport',
            name='vin_snapshot',
            field=models.CharField(blank=True, help_text='VIN كما قرأه الـ ELM327 من السيارة — للتدقيق.', max_length=17, verbose_name='VIN المقروء من السيارة'),
        ),
        migrations.AddIndex(
            model_name='vehiclediagnosticreport',
            index=models.Index(fields=['job_card', 'source'], name='inventory_v_job_car_8e6183_idx'),
        ),
        migrations.AddField(
            model_name='vehiclediagnosticphoto',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.vehiclediagnosticreport', verbose_name='التقرير'),
        ),
    ]
