# Generated by Django 4.2.30 on 2026-06-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_diag_room_persistence'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoiceitem',
            name='billing_note',
            field=models.CharField(blank=True, help_text='اختياري — تظهر للمراجعة الداخلية فقط.', max_length=200, verbose_name='ملاحظة المحاسب'),
        ),
        migrations.AddField(
            model_name='saleinvoiceitem',
            name='is_billable',
            field=models.BooleanField(default=True, help_text='افصلها لو الجزء استُخدم للفحص فقط أو كان ضماناً.', verbose_name='يُدرج في فاتورة العميل'),
        ),
        migrations.AddField(
            model_name='saleinvoiceserviceitem',
            name='billing_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='ملاحظة المحاسب'),
        ),
        migrations.AddField(
            model_name='saleinvoiceserviceitem',
            name='is_billable',
            field=models.BooleanField(default=True, verbose_name='يُدرج في فاتورة العميل'),
        ),
    ]
