# Generated by Django 4.2.30 on 2026-06-06 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0022_accountant_review_billable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number_requested', models.CharField(max_length=120, verbose_name='رقم القطعة المطلوبة')),
                ('part_name_requested', models.CharField(blank=True, max_length=200, verbose_name='اسم القطعة المطلوبة')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات للموردين')),
                ('status', models.CharField(choices=[('open', 'مفتوح — في انتظار الردود'), ('quoted', 'تم استلام عروض'), ('ordered', 'تم تحويلها إلى أمر شراء'), ('cancelled', 'ملغاة')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'طلب تسعير (RFQ)',
                'verbose_name_plural': 'طلبات التسعير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت إرسال الطلب')),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر المعروض')),
                ('quoted_eta_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مدة التوريد (أيام)')),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=240, verbose_name='ملاحظة المورد')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='inventory.rfq', verbose_name='الطلب الأصلي')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_quotes', to='inventory.vendor', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'عرض تسعير',
                'verbose_name_plural': 'عروض الموردين',
                'ordering': ['sent_at'],
            },
        ),
        migrations.AddField(
            model_name='rfq',
            name='accepted_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for', to='inventory.rfqquote', verbose_name='العرض المُعتمد'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='inventory.branch', verbose_name='فرع الطلب'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='job_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='inventory.saleinvoice', verbose_name='بطاقة الإصلاح المرتبطة'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='product',
            field=models.ForeignKey(blank=True, help_text='قد تكون فارغة لو الـ AI اقترح P/N مش موجود لدينا بعد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='inventory.product', verbose_name='القطعة (إن وُجدت في الكاتالوج)'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_rfqs', to='inventory.purchaseinvoice', verbose_name='أمر الشراء الناتج'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='rfqquote',
            constraint=models.UniqueConstraint(fields=('rfq', 'vendor'), name='uniq_rfq_vendor'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status', '-created_at'], name='inventory_r_status_73133d_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['job_card', 'status'], name='inventory_r_job_car_73452b_idx'),
        ),
    ]
