# Generated by Django 4.2.30 on 2026-06-06 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0023_rfq_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_done_at', models.DateTimeField(blank=True, null=True)),
                ('last_done_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('due_at_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('urgency', models.CharField(choices=[('overdue', 'متأخر'), ('due', 'مستحق الآن'), ('upcoming', 'قريباً')], db_index=True, default='upcoming', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('sent', 'تم إرسال تذكير'), ('dismissed', 'تم التجاهل'), ('done', 'تمت الصيانة')], db_index=True, default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('refreshed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'تذكير صيانة',
                'verbose_name_plural': 'تذكيرات الصيانة (CRM)',
                'ordering': ['urgency', 'due_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم القاعدة')),
                ('category', models.CharField(choices=[('engine_oil', 'زيت محرك'), ('brake_pads', 'فحمات فرامل'), ('spark_plugs', 'بوجيهات'), ('coolant', 'مياه تبريد'), ('transmission_oil', 'زيت فتيس'), ('timing_belt', 'سير الكاتينة / التيمنج'), ('air_filter', 'فلتر هواء'), ('cabin_filter', 'فلتر مكيف'), ('battery', 'بطارية'), ('wipers', 'مساحات'), ('general', 'عام / صيانة دورية')], default='general', max_length=24, verbose_name='نوع الصيانة')),
                ('interval_km', models.PositiveIntegerField(blank=True, help_text='مثال: 10000 — اتركه فارغاً للقواعد الزمنية فقط.', null=True, verbose_name='الفاصل الزمني (كم)')),
                ('interval_months', models.PositiveSmallIntegerField(blank=True, help_text='مثال: 6 — اتركه فارغاً للقواعد المعتمدة على الكيلومترات فقط.', null=True, verbose_name='الفاصل الزمني (أشهر)')),
                ('severity', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية — تجنّب التأخير')], default='medium', max_length=8)),
                ('applies_to_brands', models.JSONField(blank=True, default=list, help_text="فارغة = تنطبق على كل الماركات. مثال: ['BMW','MINI']", verbose_name='الماركات المنطبق عليها')),
                ('is_active', models.BooleanField(default=True)),
                ('whatsapp_template', models.TextField(blank=True, help_text='بمتغيرات: {customer}, {vehicle}, {rule}, {workshop}', verbose_name='نص رسالة WhatsApp')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'قاعدة تذكير صيانة',
                'verbose_name_plural': 'قواعد التذكير الدوري',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='servicereminderrule',
            constraint=models.CheckConstraint(check=models.Q(('interval_km__isnull', False), ('interval_months__isnull', False), _connector='OR'), name='svc_rule_has_some_interval'),
        ),
        migrations.AddField(
            model_name='servicenudge',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to='inventory.servicereminderrule', verbose_name='القاعدة'),
        ),
        migrations.AddField(
            model_name='servicenudge',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_nudges_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicenudge',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_nudges', to='inventory.vehicle', verbose_name='المركبة'),
        ),
        migrations.AddIndex(
            model_name='servicenudge',
            index=models.Index(fields=['urgency', 'status'], name='inventory_s_urgency_99535a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicenudge',
            index=models.Index(fields=['status', '-created_at'], name='inventory_s_status_452238_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicenudge',
            constraint=models.UniqueConstraint(fields=('vehicle', 'rule'), name='uniq_vehicle_rule_nudge'),
        ),
    ]
