# Generated by Django 4.2.30 on 2026-06-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_user_mfa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermfa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
