# Generated by Django 4.2.30 on 2026-07-15 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_usermfa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries', to='inventory.branch', verbose_name='الفرع'),
        ),
    ]
