# Generated by Django 4.2.30 on 2026-09-08 18:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0037_historicalproduct_wix_product_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleinvoiceitem",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00"), message="الخصم لا يمكن أن يكون سالباً"
                    )
                ],
                verbose_name="خصم الصنف",
            ),
        ),
    ]
