# Generated by Django 4.2.30 on 2026-09-08 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0038_saleinvoiceitem_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_edit",
                    models.BooleanField(
                        default=True,
                        help_text="مفعّل = يضيف/يعدّل في الفرع. مقفول = يشوف فقط (بدون تعديل).",
                        verbose_name="يقدر يعدّل؟",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_access",
                        to="inventory.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_access",
                        to="inventory.employeeprofile",
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "صلاحية فرع للموظف",
                "verbose_name_plural": "صلاحيات الفروع للموظفين",
                "unique_together": {("employee", "branch")},
            },
        ),
    ]
