# Generated by Django 4.2.30 on 2026-09-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0039_branchaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="visible_modules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="فاضية = كل ما يسمح به دوره. حدّد وحدات معيّنة لتقييد ما يراه.",
                verbose_name="الوحدات الظاهرة للموظف",
            ),
        ),
    ]
