# Generated by Django 4.2.30 on 2026-09-11 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0040_employeeprofile_visible_modules"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery/", verbose_name="الصورة"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="الصورة الأساسية"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="inventory.product",
                        verbose_name="القطعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة منتج",
                "verbose_name_plural": "صور المنتجات",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
