# Generated by Django 4.2.30 on 2026-09-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0041_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="damaged_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="سعر الهالك"
            ),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="scrap_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="سعر الخردة"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="damaged_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="سعر الهالك"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="scrap_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="سعر الخردة"
            ),
        ),
    ]
