# Generated by Django 4.2.30 on 2026-09-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0042_historicalproduct_damaged_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleInvoicePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="sales/photos/", verbose_name="صورة القطعة"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="ملاحظة"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="inventory.saleinvoice",
                        verbose_name="الفاتورة",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة فاتورة",
                "verbose_name_plural": "صور الفواتير",
                "ordering": ["id"],
            },
        ),
    ]
