# Generated by Django 4.2.30 on 2026-09-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0043_saleinvoicephoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="extra_attributes",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="حقول إضافية"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="extra_attributes",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="حقول إضافية"
            ),
        ),
    ]
