# Generated by Django 4.2.30 on 2026-09-19 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0052_journalentry_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleinvoiceitem",
            name="source_item",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_lines",
                to="inventory.saleinvoiceitem",
                verbose_name="السطر الأصلي (للمرتجع)",
            ),
        ),
    ]
