# Generated by Django 4.2.30 on 2026-09-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0054_backfill_return_source_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseinvoice",
            name="returned_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="مرتجع للمورد",
            ),
        ),
        migrations.AddField(
            model_name="purchaseinvoiceitem",
            name="returned_quantity",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="اترجع للمورد"
            ),
        ),
    ]
