# Generated by Django 4.2.30 on 2026-09-28 03:13

from django.db import migrations


def rename_cogs_account(apps, schema_editor):
    """
    Account 5001 is posted to as cost of goods sold, but the original seed
    (0009) named it «تكلفة المشتريات» — the trial balance / P&L showed the
    wrong label. Rename it only where it still carries that seed name.
    """
    ChartOfAccount = apps.get_model('inventory', 'ChartOfAccount')
    ChartOfAccount.objects.filter(code='5001', name='تكلفة المشتريات').update(
        name='تكلفة البضاعة المباعة')


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0055_purchase_returns"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name": "فرع", "verbose_name_plural": "الفروع"},
        ),
        migrations.AlterModelOptions(
            name="historicalproduct",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical صنف / قطعة",
                "verbose_name_plural": "historical الأصناف والقطع",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstocktransfer",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical تحويل مخزني",
                "verbose_name_plural": "historical التحويلات بين الفروع",
            },
        ),
        migrations.AlterModelOptions(
            name="inventory",
            options={
                "verbose_name": "رصيد مخزون",
                "verbose_name_plural": "أرصدة المخزون في الفروع",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "verbose_name": "صنف / قطعة",
                "verbose_name_plural": "الأصناف والقطع",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseinvoice",
            options={
                "verbose_name": "فاتورة شراء",
                "verbose_name_plural": "فواتير الشراء",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseinvoiceitem",
            options={
                "verbose_name": "بند فاتورة شراء",
                "verbose_name_plural": "بنود فواتير الشراء",
            },
        ),
        migrations.AlterModelOptions(
            name="saleinvoice",
            options={
                "verbose_name": "فاتورة بيع",
                "verbose_name_plural": "فواتير البيع",
            },
        ),
        migrations.AlterModelOptions(
            name="saleinvoiceitem",
            options={
                "verbose_name": "بند فاتورة بيع",
                "verbose_name_plural": "بنود فواتير البيع",
            },
        ),
        migrations.AlterModelOptions(
            name="saleinvoiceserviceitem",
            options={
                "verbose_name": "خدمة على فاتورة",
                "verbose_name_plural": "خدمات الفواتير",
            },
        ),
        migrations.AlterModelOptions(
            name="scrapdismantlingyield",
            options={
                "verbose_name": "ناتج تقطيع",
                "verbose_name_plural": "نواتج التقطيع",
            },
        ),
        migrations.AlterModelOptions(
            name="stocktransfer",
            options={
                "verbose_name": "تحويل مخزني",
                "verbose_name_plural": "التحويلات بين الفروع",
            },
        ),
        migrations.RunPython(rename_cogs_account, migrations.RunPython.noop),
    ]
