# Generated by Django 4.2.30 on 2026-10-10 17:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0056_arabic_names_cogs_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="اسم الشحنة")),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="التاريخ"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="ملاحظات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأها",
                    ),
                ),
            ],
            options={
                "verbose_name": "شحنة مجمّعة",
                "verbose_name_plural": "📦 الشحنات المجمّعة",
                "ordering": ("-date", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PurchaseShipmentCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("loading", "تحميل"),
                            ("customs", "جمارك"),
                            ("shipping", "شحن"),
                            ("insurance", "تأمين"),
                            ("travel", "سفر وتنقلات"),
                            ("food", "إعاشة / أكل"),
                            ("other", "مصاريف أخرى"),
                        ],
                        default="shipping",
                        max_length=20,
                        verbose_name="نوع المصروف",
                    ),
                ),
                (
                    "behavior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("landed", "على تكلفة المخزون"),
                            ("expense", "مصروف على الفترة"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="المعالجة المحاسبية",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="وصف (اختياري)",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "expense_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.expensecategory",
                        verbose_name="بند المصروف (للنوع مصروف)",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="inventory.purchaseshipment",
                    ),
                ),
                (
                    "treasury",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.treasury",
                        verbose_name="مدفوع من خزنة",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند مصاريف شحنة مجمّعة",
                "verbose_name_plural": "بنود مصاريف الشحنات المجمّعة",
            },
        ),
        migrations.AddField(
            model_name="purchaseinvoice",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="inventory.purchaseshipment",
                verbose_name="الشحنة المجمّعة",
            ),
        ),
        migrations.AddField(
            model_name="purchaseinvoiceextracost",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocations",
                to="inventory.purchaseshipment",
                verbose_name="من شحنة مجمّعة",
            ),
        ),
    ]
