# Generated by Django 4.2.30 on 2026-06-16 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRoomConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('diagnostic_room', '🩺 غرفة التشخيص (OBD)'), ('auto_diagnostic', '🚗 خبير التشخيص متعدد الماركات'), ('repair_atlas', '🔧 أطلس الإصلاح')], db_index=True, max_length=24, verbose_name='الغرفة')),
                ('audience', models.CharField(choices=[('shop', '🔧 فني / ورشة'), ('customer', '🚙 صاحب السيارة')], db_index=True, default='shop', max_length=10, verbose_name='النوع')),
                ('brand', models.CharField(blank=True, db_index=True, max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='ملخص (أول سؤال غالباً)', max_length=200)),
                ('turns', models.JSONField(blank=True, default=list)),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('external_session_id', models.PositiveIntegerField(blank=True, help_text='RepairSession.id أو DiagnosticScan.id إلخ', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_room_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محادثة غرفة',
                'verbose_name_plural': '💬 محادثات الغرف',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'room', '-updated_at'], name='ai_rooms_ai_user_id_b35e3c_idx'), models.Index(fields=['audience', '-updated_at'], name='ai_rooms_ai_audienc_2c0fa1_idx')],
            },
        ),
    ]
