# Generated by Django 4.2.30 on 2026-05-23 12:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='specialization',
            field=models.CharField(blank=True, help_text='مثال: سوشيال ميديا، طباعة، ثري دي', max_length=100, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='designerworklog',
            name='client_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='تقييم العميل عبر واتساب أو مباشرة', null=True, verbose_name='تقييم العميل (1-5)'),
        ),
        migrations.AlterField(
            model_name='designerworklog',
            name='title',
            field=models.CharField(help_text='مثال: بوستر افتتاح فرع جديد', max_length=200, verbose_name='عنوان العمل'),
        ),
        migrations.AlterField(
            model_name='machineprofile',
            name='electricity_rate_per_kwh',
            field=models.DecimalField(decimal_places=4, default=Decimal('2.50'), help_text='تكلفة الكيلو وات ساعة حسب شريحة الكهرباء', max_digits=8, verbose_name='سعر الكيلو وات (ج.م)'),
        ),
        migrations.AlterField(
            model_name='machineprofile',
            name='power_consumption_kwh',
            field=models.DecimalField(decimal_places=2, default=0, help_text='استهلاك الماكينة بالكيلو وات في الساعة', max_digits=8, verbose_name='استهلاك الكهرباء (kWh/ساعة)'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='description',
            field=models.CharField(help_text='مثال: طباعة 500 كارت بزنس، سوفت تاتش', max_length=300, verbose_name='وصف المهمة'),
        ),
        migrations.AlterField(
            model_name='printmaterial',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='تكلفة الوحدة (ج.م)'),
        ),
        migrations.AlterField(
            model_name='printmaterial',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الحد الأدنى'),
        ),
        migrations.AlterField(
            model_name='printmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الكمية الحالية'),
        ),
        migrations.AlterField(
            model_name='printmaterial',
            name='unit',
            field=models.CharField(default='قطعة', help_text='مثال: رول، ورقة، لتر، مل', max_length=30, verbose_name='وحدة القياس'),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الخصم'),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المدفوع'),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='printtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ'),
        ),
    ]
