# Generated by Django 4.2.30 on 2026-05-23 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_alter_designer_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='التكلفة الفعلية المحفوظة'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='actual_profit',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='صافي الربح المحفوظ'),
        ),
        migrations.AlterField(
            model_name='designerworklog',
            name='client_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='تقييم العميل عبر واتساب أو مباشرة (1 = ضعيف، 5 = ممتاز)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم العميل (1-5)'),
        ),
    ]
