# Generated by Django 4.2.30 on 2026-05-27 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printing', '0003_add_actual_cost_profit_to_printjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم البند')),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='عدد مرات الاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نوع بند',
                'verbose_name_plural': 'أنواع البنود',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.AddField(
            model_name='printjob',
            name='product_type_text',
            field=models.CharField(blank=True, help_text='اكتب نوع البند — لو موجود قبل كده هيظهرلك autocomplete', max_length=150, verbose_name='نوع البند (نص حر)'),
        ),
        migrations.AddField(
            model_name='printorder',
            name='project_file',
            field=models.FileField(blank=True, help_text='ملف التصميم الأصلي (PSD, AI, PDF, إلخ)', upload_to='print_projects/%Y/%m/', verbose_name='ملف المشروع'),
        ),
        migrations.AddField(
            model_name='printorder',
            name='project_file_2',
            field=models.FileField(blank=True, upload_to='print_projects/%Y/%m/', verbose_name='ملف إضافي 1'),
        ),
        migrations.AddField(
            model_name='printorder',
            name='project_file_3',
            field=models.FileField(blank=True, upload_to='print_projects/%Y/%m/', verbose_name='ملف إضافي 2'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='paper_size',
            field=models.CharField(blank=True, choices=[('a0', 'A0'), ('a1', 'A1'), ('a2', 'A2'), ('a3', 'A3'), ('a4', 'A4'), ('a5', 'A5'), ('b1', 'B1'), ('b2', 'B2'), ('roll_60', 'رول 60 سم'), ('roll_90', 'رول 90 سم'), ('roll_120', 'رول 120 سم'), ('roll_150', 'رول 150 سم'), ('custom', 'مقاس مخصص')], default='a4', max_length=10, verbose_name='مقاس الورق'),
        ),
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_treasury', models.BooleanField(default=False, verbose_name='مشاهدة الخزينة')),
                ('can_manage_treasury', models.BooleanField(default=False, verbose_name='إدارة الخزينة (إيداع/سحب)')),
                ('can_view_profits', models.BooleanField(default=False, verbose_name='مشاهدة الأرباح والتكاليف')),
                ('can_create_orders', models.BooleanField(default=True, verbose_name='إنشاء طلبات')),
                ('can_edit_orders', models.BooleanField(default=True, verbose_name='تعديل طلبات')),
                ('can_delete_orders', models.BooleanField(default=False, verbose_name='حذف طلبات')),
                ('can_view_all_orders', models.BooleanField(default=True, verbose_name='مشاهدة كل الطلبات')),
                ('can_manage_customers', models.BooleanField(default=True, verbose_name='إدارة العملاء')),
                ('can_view_project_files', models.BooleanField(default=False, verbose_name='مشاهدة ملفات المشاريع')),
                ('can_upload_project_files', models.BooleanField(default=True, verbose_name='رفع ملفات المشاريع')),
                ('can_manage_stock', models.BooleanField(default=False, verbose_name='إدارة المخزون')),
                ('can_view_designers', models.BooleanField(default=False, verbose_name='مشاهدة أداء المصممين')),
                ('can_use_ai_studio', models.BooleanField(default=False, verbose_name='استخدام AI Studio')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='مشاهدة التقارير')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_permissions', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'صلاحية موظف',
                'verbose_name_plural': 'صلاحيات الموظفين',
            },
        ),
        migrations.AddField(
            model_name='printjob',
            name='product_type',
            field=models.ForeignKey(blank=True, help_text='مثال: تيشرت، كارت بزنس، بنر، ماج، فلاير', null=True, on_delete=django.db.models.deletion.SET_NULL, to='printing.producttype', verbose_name='نوع البند'),
        ),
    ]
