# Generated by Django 4.2.30 on 2026-06-08 16:21

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printing', '0004_add_product_type_project_files_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, help_text='يُولّد تلقائياً', max_length=30, unique=True, verbose_name='رقم العرض')),
                ('customer_name', models.CharField(blank=True, max_length=150, verbose_name='اسم العميل (لو غير مسجل)')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='تليفون العميل')),
                ('customer_whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساب العميل')),
                ('title', models.CharField(help_text='مثال: تصميم لوجو + 500 كرت شخصي', max_length=200, verbose_name='عنوان العرض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات / شروط')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='المجموع الفرعي')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الخصم')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='نسبة الضريبة %')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الإجمالي النهائي')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'تم الإرسال — في انتظار الرد'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('expired', 'منتهي الصلاحية'), ('converted', 'تحوّل لطلب')], default='draft', max_length=15, verbose_name='الحالة')),
                ('valid_until', models.DateField(blank=True, help_text='افتراضي: 7 أيام من تاريخ الإنشاء', null=True, verbose_name='صالح حتى')),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='توكن المشاركة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ رد العميل')),
                ('converted_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotations', to='printing.printorder', verbose_name='الطلب الناتج')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_created', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('customer', models.ForeignKey(blank=True, help_text='اختياري — لو العميل مش مسجل، اكتب اسمه وتليفونه يدوياً', null=True, on_delete=django.db.models.deletion.SET_NULL, to='printing.printcustomer', verbose_name='العميل المسجل')),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض الأسعار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='مثال: تصميم لوجو احترافي بـ 3 خيارات', max_length=300, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='سعر الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الإجمالي')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='printing.pricequotation', verbose_name='العرض')),
            ],
            options={
                'verbose_name': 'بند عرض',
                'verbose_name_plural': 'بنود العرض',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
