# Generated by Django 4.2.30 on 2026-09-27 23:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0005_pricequotation_quotationline"),
    ]

    operations = [
        migrations.AddField(
            model_name="printorder",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="مبلغ الضريبة المستحق على العميل (بيتنقل تلقائياً من عرض السعر). مش بيتحسب ضمن الربح.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="الضريبة",
            ),
        ),
        migrations.CreateModel(
            name="PrintJobMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="الكمية المصروفة",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=10,
                        verbose_name="تكلفة الوحدة وقت الصرف",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_usages",
                        to="printing.printjob",
                        verbose_name="المهمة",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usages",
                        to="printing.printmaterial",
                        verbose_name="الخامة",
                    ),
                ),
            ],
            options={
                "verbose_name": "خامة مصروفة",
                "verbose_name_plural": "الخامات المصروفة على المهام",
            },
        ),
    ]
